### ISSUE TITLE
TclError: invalid command name ".!canvas"

### ISSUE THREAD

**Issue by usagi1942** [dmnfarrell/pandastable#102]
Hi all,

I have been using python and pandas for data analysis for quite a while and recently I am learning to use pandastable to facilitate my work.  I tried the following code to call a pandas dataframe, which is almost directly copied from sample code provided in the documentation.

```
class TestApp(Frame):
    def __init__(self, parent=None):
        self.parent = parent
        Frame.__init__(self)
        self.main = self.master
        self.main.geometry('600x400+200+100')
        self.main.title('Table app')
        f = Frame(self.main)
        f.pack(fill=BOTH,expand=1)
        self.df = df = pd.read_csv('test.csv')
        self.table = pt = Table(f, dataframe=df,showtoolbar=True, showstatusbar=True)
        pt.show()
        return

app = TestApp()
app.mainloop()
```

While in the 1st time it runs and works fine.  But after I closed the GUI windows and tried changing the dataframe path in the above code and calling another table, the following error will occur.

```
---------------------------------------------------------------------------
TclError                                  Traceback (most recent call last)
<ipython-input-2-964adfc47886> in <module>()
     32         return
     33 
---> 34 app = TestApp()
     35 appnew = TestNew(app.df)
     36 appnew.mainloop()

<ipython-input-2-964adfc47886> in __init__(self, parent)
     15         self.df = df = pd.read_csv('district.csv')
     16         self.table = pt = Table(f, dataframe=df,showtoolbar=True, showstatusbar=True)
---> 17         pt.show()
     18         return
     19 

\python-3.7.0.amd64\lib\site-packages\pandastable\core.py in show(self, callback)
    270         self.grid(row=1,column=1,rowspan=1,sticky='news',pady=0,ipady=0)
    271 
--> 272         self.adjustColumnWidths()
    273         #bind redraw to resize, may trigger redraws when widgets added
    274         self.parentframe.bind("<Configure>", self.resized) #self.redrawVisible)

\WPy-3701\python-3.7.0.amd64\lib\site-packages\pandastable\core.py in adjustColumnWidths(self, limit)
    711             txt = ''.join(['X' for i in range(l+1)])
    712             tw,tl = util.getTextLength(txt, self.maxcellwidth,
--> 713                                        font=self.thefont)
    714             #print (col,txt,l,tw)
    715             if tw >= self.maxcellwidth:

\python-3.7.0.amd64\lib\site-packages\pandastable\util.py in getTextLength(text, w, font)
     45     length = len(text)
     46 
---> 47     t = scratch.create_text((0,0), text=text, font=font)
     48     b = scratch.bbox(t)
     49     scratch.delete(t)

\python-3.7.0.amd64\lib\tkinter\__init__.py in create_text(self, *args, **kw)
   2499     def create_text(self, *args, **kw):
   2500         """Create text with coordinates x1,y1."""
-> 2501         return self._create('text', args, kw)
   2502     def create_window(self, *args, **kw):
   2503         """Create window with coordinates x1,y1,x2,y2."""

\python-3.7.0.amd64\lib\tkinter\__init__.py in _create(self, itemType, args, kw)
   2475         return self.tk.getint(self.tk.call(
   2476             self._w, 'create', itemType,
-> 2477             *(args + self._options(cnf, kw))))
   2478     def create_arc(self, *args, **kw):
   2479         """Create arc shaped region with coordinates x1,y1,x2,y2."""

TclError: invalid command name ".!canvas"
```

It can only be run again when I restarted the whole kernel.  May I know what can be done to tackle this issue?  Many thanks.

**Comment by dmnfarrell** [comment]
This seems to be a bug caused by a hidden canvas not being destroyed when the frame is closed. I think it's fixed now.

**Comment by usagi1942** [comment]
Thanks for your prompt return.  I tried using the new code.  While I can load another dataframe after closing the window, there is still an error message:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "\python-3.7.0.amd64\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "\python-3.7.0.amd64\lib\site-packages\pandastable\core.py", line 143, in close
    util.SCRATCH.destroy()
AttributeError: 'NoneType' object has no attribute 'destroy'`

**Comment by dmnfarrell** [comment]
Ok I made another change that should prevent this message from appearing.

**Comment by dmnfarrell** [comment]
Yes it doesn't render multi index columns properly yet. row multi index works but it doesn't group the keys like in the notebook. Also row index is display is toggled off by default. If you want this functionality I can probably add it.

**Comment by usagi1942** [comment]
Thanks.  I can leave that for now as I can somehow "flatten" the multi-index and import again.
I do not have further questions at this point and I think I can close this spread at the moment.
