### ISSUE TITLE
creating table from scratch?

### ISSUE THREAD

**Issue by pytesnim** [dmnfarrell/pandastable#103]
Hello, 
I would like to have an interactive table on my tkinter GUI, each cell will contain data that is editable and will be a variable in my app. The table that I want to create is
![my_table](https://user-images.githubusercontent.com/5729656/46865890-d6f18900-ce27-11e8-8b00-154b0686765c.png)
I couldnt find any documentation on how to add rows and columns into my pandastable.
Thank very much!

**Comment by dmnfarrell** [comment]
You can check the documentation at https://pandastable.readthedocs.io/en/latest/examples.html
The table has pandas dataframe storing the data in the background. This is updated when you edit. If you want to add rows programmatically you can do it via the table or dataframe directly and then call redraw().
