### ISSUE TITLE
Histogram issue

### ISSUE THREAD

**Issue by rpgoldman** [dmnfarrell/pandastable#109]
I am generating a histogram from about 30,000 rows, logarithmically plotted, and I get a **very** odd result.
Judging from the look of the results, my guess is that when I choose logarithmic plot for the X axis, I'm still getting bins that are sized for the non-logarithmic plot.  Or something.
[odd-log-plot.pdf](https://github.com/dmnfarrell/pandastable/files/2721976/odd-log-plot.pdf)
CSV file (with .txt extension) also attached.
[data for odd histogram.txt](https://github.com/dmnfarrell/pandastable/files/2721984/data.for.odd.histogram.txt)

**Comment by rpgoldman** [comment]
Yes, there is some odd interaction between the use of a log plot and the bin widths.  I used the "apply function" command (thanks for this!) and added a new column that was transformed by `log10`, and it fixed the plot.
If you could help me find the place where the bins arguments are computed, I will try to fix this up for log plots, at least for histograms.

**Comment by dmnfarrell** [comment]
Line 775 in plotting.py. I use the default pandas function for histograms. So bins is just passed as a number in kwargs. You can pass a sequence too which I guess you can calculate from the chosen bins.

**Comment by rpgoldman** [comment]
OK, I'll have to have a look -- I have only ever used `matplotlib.hist()` and only with log data, never with the `log=True` form.  Maybe this is what I should expect? Although it's seriously weird looking.  I'll check and get back to you.

**Comment by rpgoldman** [comment]
Sorry: I thought I had responded to this sooner.  The behavior that I hadn't expected is `matplotlib`, not `pandastable`, as you said.
