### ISSUE TITLE
Segmentation fault (core dumped) while importing

### ISSUE THREAD

**Issue by Saqhas** [dmnfarrell/pandastable#111]
I had this library working in my system. But now it is returning this error when I import it:

`import pandastable`
Segmentation fault (core dumped)

Please tell me why I am getting this error.
I have tried reinstalling it fresh.

**Comment by dmnfarrell** [comment]
You'd have to give me details of your system. Though seg faults are hard to diagnose if they give no error.

**Comment by Saqhas** [comment]
My system is :
OS: Ubuntu 16.04
RAM: 4GB(with SWAP 8 GB)
OS type: 64 bit
Processor: Intel® Core™ i3-4005U CPU @ 1.70GHz × 4 
Python version: 3.5.5

For anyother detail please inform.
The library was working perfectly. Suddenly It starting returning this error.

**Comment by dmnfarrell** [comment]
did you install with pip

**Comment by Saqhas** [comment]
Yes, I had it installed it with pip. After it started showing this error. I uninstalled it using this command:
pip uninstall pandastable

Then tried re-install using this command:
pip install pandastable

but this also gave the above error. I also tried again uninstalling through pip and installing using this command:
conda install -c dmnfarrell pandastable

But still I get the same error.

**Comment by dmnfarrell** [comment]
the conda one is out of date. you could try update your pandas and matplotlib packages with pip.
I would not mix pip and conda on ubuntu

**Comment by Saqhas** [comment]
Yes, it worked. Updating matplotlib and pands.
Thank you.
