### ISSUE TITLE
setColorByMask throws index error with non-standard index

### ISSUE THREAD

**Issue by arbitrager44** [dmnfarrell/pandastable#112]
I am working on an app where I want to use a non-standard index for the displayed dataframe. I also want to use the setColorByMask functionality. I'm getting an error when trying to do both. The following code works exactly as I'd expect, highlighting Boulder, Eugene, and San Francisco in red.

```
import pandas as pd
import numpy as np
from tkinter import *
from tkinter import ttk
from pandastable import Table, TableModel
        
class UserInterface(Frame):
    def __init__(self, parent=None):
        #set up main UI
        global pt
        self.parent = parent
        Frame.__init__(self)
        self.main = self.master
        f = Frame(self.main)
        f.grid(column=0, row=1, sticky=(E, W))
        screen_width = f.winfo_screenwidth() * 0.8
        screen_height = f.winfo_screenheight() * 0.7
        self.table = pt = Table(f, dataframe=ui_df, height = screen_height, width = screen_width)
        #ui_df.set_index('Idx', inplace=True, drop=False)
        othr_mask = ui_df['Other_num'] <= 50
        pt.setColorByMask('Location', othr_mask, 'red')
        pt.showIndex()
        pt.show()
        
pos_data = {'Location' : ['Denver', 'Boulder', 'San Diego', 'Reno', 'Portland',
    'Eugene', 'San Francisco'], 'State' : ['co', 'co', 'ca', 'nv',
    'or', 'or', 'ca'], 'Rando_num': [18, 5, 34, 11, 72, 42, 9],
    'Other_num': [11, 26, 55, 134, 88, 4, 22], 'Idx': ['a', 'b', 'c',
    'd', 'e', 'f', 'g']}
pos_df = pd.DataFrame(data = pos_data)
pos_df['Sum'] = pos_df['Rando_num'] + pos_df['Other_num']

ui_df = pos_df

#Launch Tkinter basics
root = Tk()
root.title("Test...")

mainframe = ttk.Frame(root, padding="3 3 12 12")
mainframe.grid(column=0, row=1, sticky=(N, W, E, S))
mainframe.columnconfigure(0, weight=1)
mainframe.rowconfigure(0, weight=1)
screen_width = mainframe.winfo_screenwidth() * 0.8
screen_height = mainframe.winfo_screenheight() * 0.7

ui = UserInterface(mainframe)

root.mainloop()
```

However if I unhash `ui_df.set_index('Idx', inplace=True, drop=False)` I get the following error:

> KeyError: "None of [Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object', name='Idx')] are in the [index]"

I thought of the possibility that `drop=False` is the problem in that pt is getting confused by having a duplicate in the dataframe, however if I set `drop=True` I get

>IndexError: index 5 is out of bounds for axis 0 with size 5

Thanks to the community for your help!

**Comment by dmnfarrell** [comment]
Yes row colors currently only work properly for unique indexes. If you reset the underlying index probably you should reset the colors too. I added a `resetColors` method to do this. 
This could probably be fixed to work for other indexes. You could look at the `setRowColors` and `colorRows` methods.

**Comment by arbitrager44** [comment]
10-4. I'll work on a workaround and post it here for anyone else's benefit once I get it working.

**Comment by arbitrager44** [comment]
Alright I'm sure this is something dumb, but what am I doing wrong here?

Inserted `pt.setRowColors(2, 'red')` where `setColorByMask` used to be. Now I get:

>AttributeError: 'Table' object has no attribute 'tablecolheader'

**Comment by arbitrager44** [comment]
OK I moved that line to after `pt.show()` but got no red cells. I did get two 

>A value is trying to be set on a copy of a slice from a DataFrame

warnings on the following pt code.

>rc[c][idx] = clr

and...

>self._setitem_with_indexer(indexer, value)

**Comment by arbitrager44** [comment]
Cool. I'll post anything I come up with that could be helpful. One question. In `setRowColors(self, rows=None, clr=None, cols=None)` what kind of input is it looking for in rows/cols? Index numbers or row/column names?

**Comment by dmnfarrell** [comment]
Lists of row or column numbers. Not the index names.
