### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Code4SAFrankie** [dmnfarrell/pandastable#113]
- Support for other pandas import formats (assuming this project uses pandas underneath the gui). Specifically hdf5 would be nice in order to test large datasets.
- Tools: Delete all columns with no values.
- Tools: Delete all columns with empty like values (Nan, all spaces, etc.)
- Tools: Delete selected column(s) if all values are the same.
- Tools: Copy values down for blank rows. Non-programmers often only provide the first row's value in Excel with the assumption that all blank rows below that value will fall in the same group (have the same value).
- Tools: Fit column to data width.
- Option to automatically refresh plot (would not use for large datasets but handy for colormap browsing)
- Word cloud on selected cells (case sensitive/insensitive, with stop words filtering - default words and words via separate sheet, only nouns, only verbs, etc.).
- Bag of words word counts to new sheet (case sensitive/insensitive, with stop words filtering - default words and words via separate sheet, only nouns, only verbs, etc.).
- Google maps heatmap (latitude, longitude).
- Machine learning extensions.
- Home key goes to first column; End key goes to last column; CTRL + Home goes to first column, first row; CTRL + End goes to last column, last row; Page Up key goes a page up; Page Down key goes a page down; CTRL + Page Up goes to current column's first row; CTRL + Page Down goes to current column's last row.
- As part of "add manual filter" allow multi-select drop down of distinct values in selected column.
- F4 repeats last operation on currently selected cell/column.
- Add average as a aggregate function.
- Quick conversion of string column with currency symbol and thousands separator (space or comma) to float number format. Assume currency symbol is multi-character string at start. Also cater for - and ().
- Allow axis labels to be angled 45 degrees in order to fit more categorical string values.
- For some reason replace $ does not work.
- Sort by numeric part of value, for example Ward 1 - Ward 500 must ignore the Ward part.
- Mouse wheel scroll down stops working mysteriously after scrolling a bit.

**Comment by dmnfarrell** [comment]
Thanks for the suggestions. I'll certainly try to implement some of them.
