### ISSUE TITLE
Table crashes when table height is set too small?

### ISSUE THREAD

**Issue by arbitrager44** [dmnfarrell/pandastable#116]
Hi. I may have found a minor bug. I have an app where I tried to set the height of a table dynamically and happened to set it extremely small. It caused PT to just hang. Took a little while to figure out, but once I manually set the size to something more normal, everything worked fine. It would probably be better to throw an error rather than just hang.

**Comment by dmnfarrell** [comment]
How can I replicate this error?

**Comment by arbitrager44** [comment]
I'm having a hard time recreating it in a toy example. I'll keep working and post it when I make it happen.
