### ISSUE TITLE
 setSelectedRow can't get first line of the multiple lines selected

### ISSUE THREAD

**Issue by occoder** [dmnfarrell/pandastable#117]
Try to use  setSelectedRow to select the first default start line and then press Shift key and Left click to select the end line to make a multiple lines selection.
But following exception was given:
`Traceback (most recent call last):
  File "C:\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\pandastable-master\pandastable\core.py", line 2153, in handle_left_shift_click
    self.handle_mouse_drag(event)
  File "C:\pandastable-master\pandastable\core.py", line 2166, in handle_mouse_drag
    if rowover >= self.rows or self.startrow > self.rows:
TypeError: '>' not supported between instances of 'NoneType' and 'int'`
I have to manually click the start line to initiate the multi-line selection.

**Comment by dmnfarrell** [comment]
Do you mean you are programmatically setting the start row and then manually clicking to complete the selection?

**Comment by occoder** [comment]
> Do you mean you are programmatically setting the start row and then manually clicking to complete the selection?

Exactly

**Comment by dmnfarrell** [comment]
The error tells you the problem. One of rowover, self.rows or self.startrow are None values. You can initialise them yourself before doing the selection I guess.

**Comment by occoder** [comment]
Yes. I've tried and proved that.
Anyway it'd be better that setSelectedRow could automatically set startrow in the meanwhile.

**Comment by dmnfarrell** [comment]
startrow is now set when you call setselectedrow
