### ISSUE TITLE
How to set number format e.g. '{:,.1f}' for integer/float numbers for table display?

### ISSUE THREAD

**Issue by gsudhanshu** [dmnfarrell/pandastable#118]
How to set number format e.g. '{:,.1f}' for integer/float numbers for table display?

**Comment by dmnfarrell** [comment]
You can't currently do this. I just haven't gotten round to implementing that.

**Comment by gsudhanshu** [comment]
no hurry, modified format in input dataframe

**Comment by dmnfarrell** [comment]
This is now possible with the new prefs

**Comment by gsudhanshu** [comment]
Dear Damien,

How to use this feature?

Thanks & Regards,
Sudhanshu Garg
+918851417605

**Comment by dmnfarrell** [comment]
You can right click on the table and select preferences and set float precision.

**Comment by psraman3** [comment]
Hi Damien,
   Can i able to set the number of decimal points to be display in Table via my code (instead of needing to change it in the Table pref.)?!!

**Comment by dmnfarrell** [comment]
Yes you can use config.apply_options(). See https://pandastable.readthedocs.io/en/latest/examples.html#set-preferences

**Comment by psraman3** [comment]
@dmnfarrell , Got it...Thanks....Great work..

**Comment by dbellistri** [comment]
Hi Damien,

Is there any way to configure the trailing zeroes?
E.g. show 0.500 when the value is 0.5
Thanks.

Domenico
