### ISSUE TITLE
freeze pane allowed?

### ISSUE THREAD

**Issue by gsudhanshu** [dmnfarrell/pandastable#120]
Can we do freeze pane in pandastable?

**Comment by dmnfarrell** [comment]
I'm not sure what that is. Can you explain.

**Comment by gsudhanshu** [comment]
freeze pane is a feature provided in microsoft excel, to be able to freeze view upto say column B and be able to scroll horizontally in columns C to say AAA. In this example, column A and B will always be visible. utility is that if your column A and B hold index information it will always be visible

**Comment by dmnfarrell** [comment]
You can kind of do this already for columns. If you set the columns to freeze as the index then they will not scroll.

**Comment by gsudhanshu** [comment]
how can I do it to freeze 2 columns? and can it be done through a function call?

**Comment by dmnfarrell** [comment]
You can shift or ctrl click to select multiple columns and set them as index.
Or use table.model.df.set_index(columns) then redraw.

**Comment by gsudhanshu** [comment]
well setting 2 columns as index renders them invisible in pandastable.

Anyways, I will content with a single column as freeze pane.. thanks for your help. I am marking this issue as closed.

**Comment by dmnfarrell** [comment]
It should work though. You might have to toggle the index in the row header. It should be on automatically when u set the index.

**Comment by arbitrager44** [comment]
@dmnfarrell I saw this closed issue when I was looking for a solution to something similar. You could achieve a more flexible "freeze" type behavior if you could create two tables with the scrollbars in sync. For example, say you had columns 'A' and 'B' that you want both to be frozen. You could create one table on the left that was just A and B, then the rest of your data would be a second table to the right. If the cells were always aligned (and you fooled with the formatting a bit), it would have the same effect as freezing cells in Excel. The key would be for there to be a single scrollbar that controlled both tables.

Do you know if that's possible? (I can make this a new issue if you prefer, LMK)

FWIW @gsudhanshu , if you are hard coding this into python (not in the PT app), you can just create a new column which is a mash of your two columns you want to freeze. That's what I've done in the past.

```
df['Idx'] = df['A'] + ' ' + df['B']
df.set_index('Idx', inplace=True, drop=True)
df.showIndex()
```

**Comment by dmnfarrell** [comment]
Sure it's possible. But it's a bit complicated to implement for functionality that is not hugely different than the current method using the row index. How would your suggestion be better than the behaviour shown below:

![Peek 2019-11-22 00-31](https://user-images.githubusercontent.com/7859189/69503009-5ef00080-0f0d-11ea-9517-9430a685caba.gif)

**Comment by arbitrager44** [comment]
Weird. My table isn't following that behavior. I'll play with it though.
