### ISSUE TITLE
Filter Table option in toolbar

### ISSUE THREAD

**Issue by gsudhanshu** [dmnfarrell/pandastable#121]
what should be the string query format to achieve for eg. filter out blanks in a column

**Comment by dmnfarrell** [comment]
I've changed it so you can now do this. Just type x.notnull() or zl.isnull() in the string query and it should work, where x is your col name. Alternatively you can use a manual filter and use 'is empty'.

**Comment by gsudhanshu** [comment]
Thanks, what is a manual filter?

**Comment by gsudhanshu** [comment]
The filter table option is not giving desired reults using the new dialogs.py file

**Comment by dmnfarrell** [comment]
Does this work then?

**Comment by gsudhanshu** [comment]
yes, thank you
