### ISSUE TITLE
how to align text 'center' in cells from code?

### ISSUE THREAD

**Issue by gsudhanshu** [dmnfarrell/pandastable#126]
how to align text 'center' in cells from code? for specific columns or entire table

**Comment by dmnfarrell** [comment]
You can globally set this in the preferences file. This has been updated to use a text config file. It's kept in ~/.config/pandastable/default.conf. See https://pandastable.readthedocs.io/en/latest/dataexplore.html#setting-preferences

There is a dictionary called columnformats that stores per column formatting. So do this to set the column alignment for a single column. It overrides the default:
```table.self.columnformats['alignment']['col'] = 'w' ```
