### ISSUE TITLE
Can we do wrap text in column data?

### ISSUE THREAD

**Issue by gsudhanshu** [dmnfarrell/pandastable#129]
how to do Wrap text for specific columns and set column width for that column

**Comment by dmnfarrell** [comment]
You can't yet wrap text in cells, only the column headers. Have not had time to do that. 
I assume you mean set columns widths in code. You can do that by setting the value for the col in the table.columnwidths dict: `table.columnwidths[col] = 100`

**Comment by gsudhanshu** [comment]
ok, how can I wrap text in column headers?

**Comment by dmnfarrell** [comment]
you can set `table.tablecolheader.wrap = True`
or `table.setWrap()` will toggle it on and off

**Comment by yucongo** [comment]
How difficult is it to modify the source code to wrap text in cells？I mean what needs to be done in order to achieve that? Thanks.

**Comment by dmnfarrell** [comment]
It's possible but might be a little time consuming until you are familiar with the way things are being drawn. You can check how the wrapping is done in the column header at line 98: https://github.com/dmnfarrell/pandastable/blob/master/pandastable/headers.py
The wrapping itself is just done using textwrap.wrap(). It's then a matter of making sure you don't draw too many rows of text so they don't extend out of the cell.

**Comment by yucongo** [comment]
Thanks! I'll take a look. I thought of textwrap.wrap, but don't I have to recalculate every row's height? Or do I just set a maximum row height for all rows? As I understand it, pandastable draws cells on a tkinter's canvas. It's a bit difficult for me to wrap my head around the whole thing. I am dealing with some text process problem and would like to make use of pandastable (to use a dataframe as a model).
