### ISSUE TITLE
ImportError: C extension: No module named 'pandas._libs' not built

### ISSUE THREAD

**Issue by SchuppiM** [dmnfarrell/pandastable#132]
Just started to ge familiar with Panda tables, so I created a ver Basic code but already run into an error.
Out of this code:
from pandastable import Table

self.PandaTable = Table(self.UebersichtsFenster4)
self.PandaTable.place(x=10, y=10)
self.PandaTable.show()

I got this error:
Traceback (most recent call last):
  File "C:/Users/mschuppisser.EAD/Data/My Data/Python/Test Applikation/Test Applikation.py", line 17, in <module>
    import pandas as pd
  File "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: No module named 'pandas._libs' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

Any thoughts what I'm doing wrong?
Thx a ton!

**Comment by dmnfarrell** [comment]
This is a  pandas error. You may not have installed it properly. You should usually install with pip.

**Comment by SchuppiM** [comment]
ok, I uninstalled it and then installes it again with pip.exe install Pandas.
I got:
Installing collected packages: pandas
Successfully installed pandas-0.24.2
Now it's working even I installed it the same way 2 hours ago!
Thx a ton!
