### ISSUE TITLE
incompatible with latest version of pandas

### ISSUE THREAD

**Issue by mgeorgiadis** [dmnfarrell/pandastable#133]
Hello, 

I'm running into issues running pandastable with the latest version of pandas (>0.24).  When I try to import pandas table with 
`from pandastable import Table, TableModel`

I get the following error

```
    from pandastable import Table, TableModel
  File "C:\Python\WPy64-3720\python-3.7.2.amd64\lib\site-packages\pandastable\__init__.py", line 5, in <module>
    from .core import *
  File "C:\Python\WPy64-3720\python-3.7.2.amd64\lib\site-packages\pandastable\core.py", line 42, in <module>
    from .plotting import MPLBaseOptions, PlotViewer
  File "C:\Python\WPy64-3720\python-3.7.2.amd64\lib\site-packages\pandastable\plotting.py", line 33, in <module>
    from pandas.tools import plotting
ModuleNotFoundError: No module named 'pandas.tools'
```

According to the stackoverflow post below, it looks like in new versions of pandas >= 0.24, they moved plotting to `pandas.plotting` as opposed to `pandas.tools.plotting`.

https://stackoverflow.com/questions/54473018/where-is-pandas-tools

I'm using pandas v0.24.2, pandastable v0.11.0, WinPython 3.7.2

**Comment by dmnfarrell** [comment]
This should be fixed but I haven't yet pushed an update to pip. Will do that soon. thanks.

**Comment by arbitrager44** [comment]
Does this help?

https://stackoverflow.com/questions/54473018/where-is-pandas-tools

**Comment by dmnfarrell** [comment]
sorry what I meant is, this is fixed in the git repository but I haven't updated to pip yet.

**Comment by mgeorgiadis** [comment]
Yeah apologies for not writing back, I installed using pip and the latest version on GitHub and everything worked properly.
