### ISSUE TITLE
Ctrl+Click Highlight Box Unexpected Behavior

### ISSUE THREAD

**Issue by Cr8on0** [dmnfarrell/pandastable#134]
The behavior of the selection box after Ctrl+Click could be somewhat confusing to users. In the image included, the row highlight correctly shows that rows 7, 10, 12, and 14 were selected using Ctrl+Click, but the blue outline box appears to indicate that all of the rows between 7 and 14 were selected. When Shift+Click is used to select all rows between 7 and 14, the box looks the same. I have confirmed that this is only an issue with the highlight box using table.getSelectedDataFrame(), which returns only the expected information from rows 7, 10, 12, and 14. 

![pandastable_CtrlClickBehavior](https://user-images.githubusercontent.com/50384272/57336701-16453700-70e4-11e9-9014-212acc176f69.PNG)

I believe (but am not certain) that the relevant Source Code is below, but I am not exactly sure how to edit it to change this behavior.

    def handle_left_ctrl_click(self, event):
        """Handle ctrl clicks for multiple row selections"""

        rowclicked = self.get_row_clicked(event)
        colclicked = self.get_col_clicked(event)
        if 0 <= rowclicked < self.rows and 0 <= colclicked < self.cols:
            if rowclicked not in self.multiplerowlist:
                self.multiplerowlist.append(rowclicked)
            else:
                self.multiplerowlist.remove(rowclicked)
            self.drawMultipleRows(self.multiplerowlist)
            if colclicked not in self.multiplecollist:
                self.multiplecollist.append(colclicked)
            self.drawMultipleCells()
        return

If this is the desired behavior and therefore does not warrant a change to the source code, some guidance on how to alter this behavior for my specific use case would be greatly appreciated. The desired behavior would be to only outline the cells selected with Ctrl+Click.

**Comment by dmnfarrell** [comment]
This is the intended behaviour partly because implementing what you want was trickier. Also the selected rows are still highlighted so a user can see only some rows are selected. I agree it could be a bit confusing.
Yes I'd suggest you subclass the table and override the `drawMultipleCells()` method. Instead of drawing one rectangle you would have to draw a separate one for each row. You would loop over `self.multiplerowlist`

**Comment by Cr8on0** [comment]
Apologies for the delayed response in closing this issue; I have been on another project and haven't had an opportunity to implement your suggestions. I believe that the original question has been addressed however, so I will close it.
