### ISSUE TITLE
Could you confirm below if it is possible or not for this application?

### ISSUE THREAD

**Issue by YogeshSakpal** [dmnfarrell/pandastable#135]

**Comment by YogeshSakpal** [comment]
Hi Damien Farrell,
Nice for the demo file, I have couple question to ask to you and please tell me if it doable or not with pandastable.
1.	Can we add loading page once we launch the application?
2.	Primary Key selection interface – 
a.	The user will be shown all the variables having all distinct values as potential unique key.
b.	The user will also be shown all the variables having 90% distinct values as potential unique key. Selecting this as unique key will require any one of the variables from column a to be combined with it to get 100% unique values.

3.	Day to Day comparer of uploaded files:-
In order to compare two consecutive days upload, the user has to upload the second days file. The summary of the file will be displayed as in first upload.
	This second day’s file will use the same primary key for comparison.
4.	Can we change the look and feel of the application currently having?
5.	Is there any integration possible with MongoDB kind of database?

**Comment by dmnfarrell** [comment]
Hi. Most of these could probably only be handled with a plugin for the specific functions. If you know python you could do it. I can advise u if u want to try that.

Can we add loading page once we launch the application?

Do you mean a progress bar?

Primary Key selection interface –
a.	The user will be shown all the variables having all distinct values as potential unique key.
b.	The user will also be shown all the variables having 90% distinct values as potential unique key. Selecting this as unique key will require any one of the variables from column a to be combined with it to get 100% unique values.

I think these are specific functions for your database?

Day to Day comparer of uploaded files:-
In order to compare two consecutive days upload, the user has to upload the second days file. The summary of the file will be displayed as in first upload.
This second day’s file will use the same primary key for comparison.

Also rather specific.

Can we change the look and feel of the application currently having?

No

Is there any integration possible with MongoDB kind of database?

You would have to write it as a plugin.

**Comment by YogeshSakpal** [comment]
Hi Damien,
Thanks for your quick turnaround!!!
I have some questions on Look and feel point of view.
1.	Is it possible to change application Title bar with some other color? for example, please find below snapshot.
2.	Is it possible to change application Menu Bar with some other color?
3.	Can we arrange the spacing between the components? For example, under global labels we have title followed by input box, xlabel, ylabel and zlabel. 

Figure – Tool Layout
4.
![Capture12](https://user-images.githubusercontent.com/33949114/59326020-ce2cbc00-8d02-11e9-91ae-a09a382587bf.JPG)

Appreciate your help here.

**Comment by dmnfarrell** [comment]
Hi

This app uses tkinter which has very limited ability to alter look and feel. Theoretically you can change the color of the menu bar. If you know some python it's possible. You cannot change the title bar of the window as that is external to the app and is a part of the theme of your own system. You can alter that system-wide in whatever version of linux you use.
Spacing adjustment is done automatically the way I added the widgets. Why do you need to change the spacing though?

**Comment by YogeshSakpal** [comment]
Hi Damien,

Thanks your quick response.

Regarding the change in color of menu bar i have tried below code but not able to do it.
Code - 
    def createMenuBar(self, bg='Green'):
        """Create the menu bar for the application. """

        self.menu = Menu(self.main, **bg="#353759"**)
        file_menu = Menu(self.menu,tearoff=0)

Expected output would be -  
![Capture123](https://user-images.githubusercontent.com/33949114/59349833-377af200-8d38-11e9-946e-60897bd8f19d.JPG)

Also in spacing adjustment i want to reduce the space of each component which currently having. Please guide here as well.

**Comment by dmnfarrell** [comment]
What you want is to manipulate the ttk styles of widgets. I do not really do this except in a limited way so don't know much about it.
These may be of help:

https://docs.python.org/3/library/tkinter.ttk.html
https://tkdocs.com/tutorial/styles.html

You could probably use the same method to change the spacing adjustment.

**Comment by YogeshSakpal** [comment]
Hi Damien, 

Could you please guide me for changing Menu Bar bachground ribbon color as #353759?

Appreciate your quick help.

Expected output would be -
Capture123

**Comment by dmnfarrell** [comment]
As I said I don't have much experience with that. The only code I have is a function for setting the style on a label like this:
```
bg = Style().lookup('TLabel.label', 'background')
w.configure(fg='black', bg=bg,
                     activeforeground='white', activebackground='#0174DF')
```
You can check the ttk documentation for how to do this with menus, it should be possible.

**Comment by YogeshSakpal** [comment]
Hi Damien,

Good Day!!!

Thanks for quick reply. 

I have some questions related to pandastable, could you please tell me if those points are doable in existing application?

Questions are - 
1. Will we reduce the font size in the grid on left side table?
2. Can we change Line Graph to be made more lighter with more glossier colours?
3. Can we remove Marker borders around the plotted points in the scatter plot?
4. Can we do left alignment for plot types, binning, group by and group by2?
5. Spacing were not working between the addButton(), could you please let me know where we can make changes?
6. Can we permanently fix lower bottom options on right hand side to vertical as we are doing now through change orientation button?

**Comment by dmnfarrell** [comment]
I've answered these below though it seems you want changes to the interface that are beyond the scope of the package functionality. I am guessing you've forked this project and want to customise the app? If you want to customise tkinter I would use the tkinter docs.

Will we reduce the font size in the grid on left side table?
If you mean the row index, then this is set with the general font size of the table or as you zoom in and out.

Can we change Line Graph to be made more lighter with more glossier colours?
I'm not sure what you mean. Line colors are set in the plotting dialog underneath (colormap). You can also set the transparency.

Can we remove Marker borders around the plotted points in the scatter plot?
Yes, set line width to 0.

Can we do left alignment for plot types, binning, group by and group by2?
Left alignment of what?

Spacing were not working between the addButton(), could you please let me know where we can make changes?
You would have to be more specific here. This seems like a tkinter problem.

Can we permanently fix lower bottom options on right hand side to vertical as we are doing now through change orientation button?
Yes you could do that, I think u can set self.toolslayout= 'vertical' in the plotting dialog when you create it.

**Comment by YogeshSakpal** [comment]
Thanks Damien,

I am just forking in the editor for some visualization, how this has been implemented. Again i have couple of questions to you while on model fitting/ model creation through code.

1. While working on model creation i am getting some errors which is more towards patsy libraries which i am not able to resolved.

Error log
![Error log](https://user-images.githubusercontent.com/33949114/59613135-ffaaea80-913b-11e9-9345-e751c621e3c8.JPG)

Snapshot - 
![Layout error](https://user-images.githubusercontent.com/33949114/59613157-0a657f80-913c-11e9-8a4a-45702b791fa3.JPG)

2. Code file i am referring - stats.py
[stats.zip](https://github.com/dmnfarrell/pandastable/files/3297490/stats.zip)

Appreciate your help in resolving this.

**Comment by YogeshSakpal** [comment]
HI Damien,

Good Day!!!

Any help on above points ?

**Comment by dmnfarrell** [comment]
Hi

Yes it seems to be a bug with newer versions of statsmodels. I'll have to look at it.

**Comment by dmnfarrell** [comment]
This is a problem with statsmodels. The easiest solution is to install their latest version using: 
`sudo pip install git+https://github.com/statsmodels/statsmodels`
or use pip3 if python3 on ubuntu.
