### ISSUE TITLE
Row Selection Not Putting Entire Row into SelectedDataFrame

### ISSUE THREAD

**Issue by Cr8on0** [dmnfarrell/pandastable#136]
When selecting an entire row, i.e., clicking on the row number, no data is output when using table.getSelectedDataFrame(), but the row is highlighted in the table. See screenshots below:

![pandastable_RowSelectionNotSelectingData_Annotated](https://user-images.githubusercontent.com/50384272/59118389-3c413f80-890d-11e9-958b-581782f2cbf1.PNG)

The red box indicates where clicked. The other rows were successfully highlighted using Shift+Click.

![pandastable_SelectedDF](https://user-images.githubusercontent.com/50384272/59118401-4400e400-890d-11e9-990a-4b2b5913d826.PNG)

The above was generated with the code:
selectedDF = table.getSelectedDataFrame()

 If data from a particular column is first selected, and then the row number is selected, only data from that column for the selected row will be output to the selected df. 

In contrast to the selection box issue I raised in #134 , which I believe can be trained around (or I will try the fix you suggested), I think this behavior is too counterintuitive for my application. Selecting an entire row will likely be the most common user input, and the rest of the application relies on the output of table.getSelectedDataFrame().

**Comment by Cr8on0** [comment]
Small note that selectedDF is shifted by one wrt the row numbers because the table rows start at 1, but the df starts at 0.

**Comment by dmnfarrell** [comment]
Yes perhaps getSelectedDataFrame() should return the entire row if only one col or none are selected. However if multiple columns are selected users may want the current behaviour. Perhaps it would better to implement a get SelectedRows method as well. What do you think?
BTW the row numbers are different to the index and are just spreadsheet type numbering (starting from 1). You can display the index instead, which can be anything.

**Comment by Cr8on0** [comment]
I see what you mean. I think the getSelectedRows method would definitely work for my application and may also be helpful to others. Both the getSelectedRows df and the getSelectedDataFrame df would need to be checked, if selections are needed (as in my case), but that will be easy to implement.

Oh, right, apologies, I wasn't trying to imply an error with the index numbers, just clarifying that my two screenshots represented the same data. 

Would you be willing to implement a getSelectedRows method then?

**Comment by dmnfarrell** [comment]
Ok that's added. You can check it works ok.

**Comment by Cr8on0** [comment]
This works perfectly! Thanks so much for the quick response.

On an unrelated note, I noticed that the docs state that you may be able to freeze the app on Anaconda. I know that was a while back, so you may have tested it/received word that it works, but, in case not, I am using Python 3.7 on Anaconda (Spyder), and I have been able to successfully port my tkinter GUI that includes a pandastable to .exe using PyInstaller. 

For anyone who stumbles across this, there is an issue with the version of PyQt5 expected by PyInstaller and the one available in Anaconda, so I have used --exclude-module PyQt5 in my pyinstaller command, which has not had an impact on the operation of pandastable. If PyQt5 is required, I believe there is another workaround, but excluding it is much simpler if it's not needed (and you can break your Anaconda distribution if you're not careful). 

Again, thanks so much for the help!

**Comment by dmnfarrell** [comment]
Glad it works.
No I haven't tried to build on anaconda at all. I don't really use it myself. I still use cxfreeze myself. If you want to post the recipe/script you used I could put it in the documentation.
Why is PyQt5 needed since it is not a dependency of this package? Is it a feature of pyinstaller/anaconda?

**Comment by Cr8on0** [comment]
PyQt5 is definitely not needed. There is a problem with the PyInstaller PyQt5 hook when using PyInstaller with Anaconda, so it needs to be excluded (or I will post a link to another work around below).

Sure; the general outline follows:

This has worked for me with Python 3.7, Conda 4.6.14, PyInstaller 3.4, (and Spyder 3.3.x) for a tkinter GUI including a pandastable.

From the Anaconda Prompt:

pip install pyinstaller
cd C:\WhateverDirectoryYourGUIISIn
pyinstaller --exclude-module PyQt5 --windowed --onedir myGUI.py

I believe the  prescribed import is conda install pyinstaller because conda and pip don't always play nice, but I haven't had any problems with pip for this purpose.

--windowed is an option that will exclude the command prompt popup on .exe startup.

--onedir is one folder; it can be replaced with --onefile for one file, but executables created this way seem to take a bit longer to open.

--exclude-module PyQt5 is because the PyInstaller hook does not recognize PyQt5 in Anaconda, so the build will fail without this exclusion. I believe another work around can be found at the link below, but excluding PyQt5 worked fine for me.
https://github.com/pyinstaller/pyinstaller/issues/3740

 All available pyinstaller flags can be found at:
https://pyinstaller.readthedocs.io/en/v3.4/usage.html

If data files are imported by the GUI, there are two options. If neither is satisfied, the .exe won't open:
https://pythonhosted.org/PyInstaller/spec-files.html#using-spec-files
or
Copy the needed files into the same directory as the .exe 

Depending on your machine and the complexity of the GUI, the PyInstaller build can take a while. After successfully running pyinstaller, a new folder called dist will be placed in the original directory, and the compiled .exe will be here (either in a file or folder).
