### ISSUE TITLE
griddata cannot be imported from matplotlib.mlab

### ISSUE THREAD

**Issue by likit** [dmnfarrell/pandastable#138]
Hi, It seems like griddata has been moved or deprecated from Matplotlib version 3.1.0.

**Comment by dmnfarrell** [comment]
Yes I am fixing that. Are you using python 2 or 3?

**Comment by likit** [comment]
Thanks, I'm using Python 3.

**Comment by dmnfarrell** [comment]
Does this error stop you from using the package? I have moved the import statement into functions so it shouldn't trigger unless you use some 3d plots.

**Comment by mxtm** [comment]
> Does this error stop you from using the package? I have moved the import statement into functions so it shouldn't trigger unless you use some 3d plots.

It is stopping me from using the package; I'm attempting to "show" a Table object (on Python 3 also) and I am getting this error as well.

**Comment by dmnfarrell** [comment]
@mxtm: This is updated but I will have to push a new update if you are using pip to install.

**Comment by mxtm** [comment]
@dmnfarrell I am currently using pip to install, but in the case that you weren't planning on pushing an update soon, I can manually install the updated package

**Comment by dmnfarrell** [comment]
@mxtm I will try to update soon as others using pip will get this error. In the meantime you could install from the latest git version.

**Comment by likit** [comment]
Thanks. I try it out again later.
