### ISSUE TITLE
Can you demonstrate "filter rows" functionality?

### ISSUE THREAD

**Issue by JayLi2018** [dmnfarrell/pandastable#139]
As the title says, i am having trouble using your "filter rows" function. what are the rules for writing this "String query" in order to get the table filtered? 

Thank you so much, your hard work made my life easier!

**Comment by dmnfarrell** [comment]
You just type out the names of columns with simple boolean conditions. It assumes your columns don't have spaces in them.
Have you seen this page: https://pandastable.readthedocs.io/en/latest/dataexplore.html#filtering-tables
If you are still confused I can explain it more fully.

**Comment by JayLi2018** [comment]
thanks for your quick response!  so i am thinking to write something like 'column contains some string', is that possible?

Also i am having another question. is it possible to show part of the table while still be able to use the hidden columns?
specifically, lets say my original dataframe has (A,B,C) 3 columns, but i only want users see (A,B) but in the backend i still need column c to be able to get my job done, i've tried only pass df = df[A,B] but it seems after sorting, filtering etc, the result index cannot match to the original index which means i lost the access to column c

**Comment by JayLi2018** [comment]
for example i wrote "crime_type contains 'ASSAULT'" it did not work and saying it's 'invalid syntax'

**Comment by dmnfarrell** [comment]
It should accept python syntax also. I haven't documented it well. So for example you can try:
`crime_type.str.contains("ASSUALT")`

**Comment by JayLi2018** [comment]
I tried your solution above it says:
TypeError: 'Series' objects are mutable, thus they cannot be hashed

**Comment by JayLi2018** [comment]
But if i leave first textbox  as empty and put this query using "manual filter" it works

**Comment by dmnfarrell** [comment]
Yes it will work using a manual filter. 
Are you using this in windows or linux?

**Comment by JayLi2018** [comment]
Linux(Ubuntu)

**Comment by dmnfarrell** [comment]
Which version of pandas? You caN check this in the help menu.

**Comment by JayLi2018** [comment]
i am using pandas 0.23.4, which is relatively old version, but i remember when using new pandas version there's an issue for importing pandas.plotting or something

**Comment by dmnfarrell** [comment]
I think that's the latest version of pandas. It's a bit strange that that command doesn't work then. The plotting import problem should be fixed in the latest version of pandastable.

**Comment by JayLi2018** [comment]
hi, i just updated pandastable version, that command now works! thank you for your help!
