### ISSUE TITLE
setRowColors, cols='all' leaves certain cells original color

### ISSUE THREAD

**Issue by arbitrager44** [dmnfarrell/pandastable#140]
Has anyone experienced setRowColors seemingly skipping certain cells? The image below shows what's happening.

![image](https://user-images.githubusercontent.com/46244905/59562980-15b49000-9002-11e9-9f7e-835a43366e9f.png)

Here is the code that's setting these cells (`medit` is the name of my pandastable).

```
        types = {1:'mediumblue', 2:'lightgreen', 3:'aquamarine',
                4: 'peru', 5:'indianred', 6: 'orangered',
                7:'orchid'}
        for t in types:
            mask = self.medit.model.df['Type'] == t 
            m_list = mask.tolist()
            color_rows = [r for r, e in enumerate(m_list) if e]
            self.medit.setRowColors(rows=[color_rows], clr=types[t], cols='all')
```
However I don't think it is code-specific since if I do something very basic like:

```
self.medit.setRowColors(rows=[11], clr='violet', cols='all')
```
(Where row 11 is the first one in the image that is fouling up) it indeed turns the REST of the row violet, but not those first few cells. 

My hunch is there's some kind of escape character or some such that is confusing PT, but I can't figure out what could be different in these two rows just from looking at the underlying Dataframe. FWIW, if I resort the underlying data such that a different set is in row 11, the same color problem happens in row 11. It isn't following the text/numbers around. It is the location. Has anyone seen anything like this before?

**Comment by dmnfarrell** [comment]
You could look at the `colorRows` method that does the actual coloring. It's called every time there is a redraw. There might be a bug in it. Could also be related to your column names perhaps, you don't show them in the example.

**Comment by arbitrager44** [comment]
OK I'll play with it. I did try re-arranging the columns to test for column names causing it, and the same cells were problematic. I.e., the problem didn't follow the column name, it stayed in the exact same position.

**Comment by hboghbog** [comment]
FWIW, I'm seeing the same issue. When I scroll, some of them get fixed, but when I scroll back, the issue comes back. For me the issue always happens on the same rows/cells.

Before Scrolling:
![image](https://user-images.githubusercontent.com/63732285/79352405-69805600-7eff-11ea-848d-8eb75ea2b620.png)

After Scrolling:
![image](https://user-images.githubusercontent.com/63732285/79352473-84eb6100-7eff-11ea-8797-1c464dc13f1b.png)

**Comment by machinelearning2014** [comment]
@arbitrager44, @hboghbog , @dmnfarrell , has anyone managed to fix this issue, as there appears to be a pattern, i.e. row 12 and row 22

**Comment by hboghbog** [comment]
Actually I was just running that same program yesterday and still have the issue. I never ended up chasing it down.

**Comment by machinelearning2014** [comment]
I think I found the bug. In method colorRows, the call to the class method self.drawRect, change arg from delete=1 to delete =0


   def colorRows(self):
        """Color individual cells in column(s). Requires that the rowcolors
         dataframe has been set. This needs to be updated if the index is reset"""

        #print (self.rowcolors)
        df = self.model.df
        rc = self.rowcolors
        rows = self.visiblerows
        offset = rows[0]
        idx = df.index[rows]
        #print(idx)
        #print (rc)
        for col in self.visiblecols:
            colname = df.columns[col]
            if colname in list(rc.columns):
                colors = rc[colname].loc[idx]
                for row in rows:
                    clr = colors.iloc[row-offset]
                    if not pd.isnull(clr):
                        #print(row,col,clr)
                        #self.drawRect(row, col, color=clr, tag='colorrect', delete=1)
                        self.drawRect(row, col, color=clr, tag='colorrect', delete=0)
   
        return

**Comment by machinelearning2014** [comment]
I put through a commit request for this

**Comment by hboghbog** [comment]
Nice! I just gave that a try and it is working after a quick smoke test.

**Comment by collinsavalon** [comment]
not related here, desperate to know how can use different precision in each column. thanks
