### ISSUE TITLE
deprecated library

### ISSUE THREAD

**Issue by Swantalker** [dmnfarrell/pandastable#142]
in windows I am encountering the following issue, and whatever I try to fix the issue turn out useless, please can you give me a solution

I get the following Exception

Exception has occurred: Import Error
cannot import name 'griddata' from 'matplotlib.mlab' 

while running the following simple call

from pandastabel import Table, TableModel

**Comment by dmnfarrell** [comment]
Did you install using pip?

**Comment by Swantalker** [comment]
Hi, it is acrually for my brother who is not that good in english, he is a programmer with 30 yrs experience and yes he did install it with pip on a new brand machine

Sent from my iPhone

On 2 Jul 2019, at 12:35, Damien Farrell <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you install using pip?

**Comment by dmnfarrell** [comment]
This will be updated very soon on pip and should fix this problem.

**Comment by Swantalker** [comment]
[image1.png]

This is the full message
Sent from my iPhone

On 2 Jul 2019, at 13:34, Damien Farrell <notifications@github.com<mailto:notifications@github.com>> wrote:


This will be updated very soon on pip and should fix this problem.

**Comment by Swantalker** [comment]
Thx

Sent from my iPhone

On 2 Jul 2019, at 13:34, Damien Farrell <notifications@github.com<mailto:notifications@github.com>> wrote:


This will be updated very soon on pip and should fix this problem.

**Comment by michaelshapiro1** [comment]
From what I can see, matplotlib.mlab.griddata does not exist in Python3 version of matplotlib which is now 3.1.  This is likely your issue.  You can either downgrade matplotlib.

However, I think this can be changed to support scipy.interpolate.griddata instead which has a different function call.  I have modified a local copy to do this and it does seem to work but I am not sure how to make this backward compatible so I thought I would post here to let everyone know what I found.

**Comment by Swantalker** [comment]
Thank u very much

Sent from my iPhone

On 2 Jul 2019, at 15:47, michaelshapiro1 <notifications@github.com<mailto:notifications@github.com>> wrote:


From what I can see, matplotlib.mlab.griddata does not exist in Python3 version of matplotlib which is now 3.1. This is likely your issue. You can either downgrade matplotlib.

However, I think this can be changed to support scipy.interpolate.griddata instead which has a different function call. I have modified a local copy to do this and it does seem to work but I am not sure how to make this backward compatible so I thought I would post here to let everyone know what I found.

**Comment by Swantalker** [comment]
Morning,

My brother did try everything suggested but he continues to encounter the same error, no much to added to the previous, only maybe it could be usefull, the version that get install is the 0.12.0

Thanks in advance

Swantalker

Sent from my iPhone

On 2 Jul 2019, at 15:47, michaelshapiro1 <notifications@github.com<mailto:notifications@github.com>> wrote:


From what I can see, matplotlib.mlab.griddata does not exist in Python3 version of matplotlib which is now 3.1. This is likely your issue. You can either downgrade matplotlib.

However, I think this can be changed to support scipy.interpolate.griddata instead which has a different function call. I have modified a local copy to do this and it does seem to work but I am not sure how to make this backward compatible so I thought I would post here to let everyone know what I found.

**Comment by dmnfarrell** [comment]
version 0.12.1 is now in pip so you can update to that and it should fix the problem.

**Comment by Swantalker** [comment]
Thx

Sent from my iPhone

On 4 Jul 2019, at 13:16, Damien Farrell <notifications@github.com<mailto:notifications@github.com>> wrote:


version 0.12.1 is now in pip so you can update to that and it should fix the problem.
