### ISSUE TITLE
Decision Tree - MultiClass Classification

### ISSUE THREAD

**Issue by YogeshSakpal** [dmnfarrell/pandastable#143]

**Comment by dmnfarrell** [comment]
Yogesh 

This would have to be implemented as a plugin probably using sklearn I imagine. Basically anything like this that can be done with pandas/sklearn/numpy/scipy could be implemented as a plugin if you wanted it. For example there is some code for doing PCAs etc. here: https://github.com/dmnfarrell/pandastable/blob/master/pandastable/plugins/mdanalysis.py
But I never got round to finishing it. You could use this or one of the other plugins as a template.

**Comment by YogeshSakpal** [comment]
Hi Damien, 

Thanks for quick response. 

Instead logistic regression can we fit decision tree from sklearn. What do think will work? 

As per below code -

def logistic_regression(X, ax, **kwargs):

    idx = X.index
    cla = pd.Categorical(idx)
    y = cla.codes
    from sklearn import linear_model
    logreg = linear_model.LogisticRegression(C=1e5)
    X = X.values
    X = X[:, :2]
    logreg.fit(X, y)

**Comment by dmnfarrell** [comment]
Sure that will work but what is the relevance to pandastable? Are you trying to build an interface to do this type of fitting?
