### ISSUE TITLE
Some questions on Regression Model

### ISSUE THREAD

**Issue by YogeshSakpal** [dmnfarrell/pandastable#145]

**Comment by YogeshSakpal** [comment]
Hi Damien,

Do let me know if this is possible in this application?

**Comment by dmnfarrell** [comment]
Yogesh
This is certainly implementable in Python and as I said before you could use a plugin to provide it as a tool inside dataexplore. There are plugin examples in this repository. You could tie the tool data to the table being displayed and plot the results in the plot frame. Of course you could also write your own application to do this.

**Comment by YogeshSakpal** [comment]
Hi Damien,

Could you please elaborate your answer for 3 questions which is doable with
existing application?

I mean especially for first question, second question.

Appreciate your response.

**Comment by YogeshSakpal** [comment]
Hi Damien,

Could you please elaborate your answer for 3 questions which is doable with
existing application?

I mean especially for first question, second question.

1. Initially model will consider all variables other than output variable as input variables for training purpose. This model we can call as Full model with all individual inputs and second order interaction terms. ====> Let us consider IRIS Dataset, here how to write formula that will consider all variables other than output variable as input variables, for example => Sepal_length ~ (what could be here, other than  i.e Sepal_width + Petal_length + Petal_width), which operator will work here?

Appreciate your response.

**Comment by dmnfarrell** [comment]
If you're looking to do this kind of linear regression maybe you should use R. I implemented this model fitting tool in dataexplore but I doubt many people use it. I was actually thinking of removing it. It does work but its not that flexible I guess. Its based on statsmodels library, so that's the syntax you should follow for writing models. https://www.statsmodels.org/stable/index.html
