### ISSUE TITLE
Set index column width?

### ISSUE THREAD

**Issue by arbitrager44** [dmnfarrell/pandastable#151]
If I display the index of my table using `showIndex()` is there a way to set the width of that column? `columnwidths` seems to only work on columns of the model df.

**Comment by dmnfarrell** [comment]
Indexes are displayed seperately yes. The row header width is currently set dynamically to fit the contents where possible. The rowheader object has an attribute maxwidth that you can change which should work. You can only set that after the show() method is called:
```
table.show()
table.rowheader.maxwidth = 100
table.redraw()
```

**Comment by arbitrager44** [comment]
Great thanks!
