### ISSUE TITLE
Hi, i want to display the index of the pd DataFrame in the PandasTable. How can i enable this in my code.

### ISSUE THREAD

**Issue by psraman3** [dmnfarrell/pandastable#152]

**Comment by dmnfarrell** [comment]
use table.showIndex()
https://pandastable.readthedocs.io/en/latest/pandastable.html#module-pandastable.core

**Comment by psraman3** [comment]
Hi, @dmnfarrell . Thanks for your quick reply. Indeed that line of code helped to show the Index values in the PandasTable. However, I have assigned a name for the Index (at header), and that Index name is not displayed !!

**Comment by psraman3** [comment]
![image](https://user-images.githubusercontent.com/54652862/67146972-18cad000-f2c3-11e9-8514-e17b5be0054a.png)
In this image, i need the Index name = Time, which i have it assigned in my pandas df.
 Thanks in advance...

**Comment by psraman3** [comment]
Hi, @dmnfarrell , i managed to bring the Index name displayed in the PandasTable. So this issue is solved. Thanks.
   On another note, I wish to set the float precision to 5. And, I tried various methods as described at https://github.com/dmnfarrell/pandastable/issues/118#issuecomment-526136421. But the effect is not seen. Unlike last time, where i was reading from a csv file to display in Pandastable, now i am directly reading a pandas df.
   Kindly let me know a solution for this. Thanks in advance...

**Comment by arbitrager44** [comment]
@psraman3 You mostly have to manipulate your df using pandas and then display using PandasTable. In this case, I'd round the columns in your df to 5 decimals before displaying in PT.

**Comment by dmnfarrell** [comment]
The precision option should work though. This works for me:
```
pt = Table(frame, dataframe=df)
options = {'colheadercolor':'green','floatprecision': 5}
pt.show()
config.apply_options(options, pt)
```

**Comment by psraman3** [comment]
Hi, @arbitrager44 Thanks for the suggestion. I already tried that option to round df, with following codes:
    # output_file_combined.round(5)
    pd.set_option('precision', 5)
Although the df display correctly to a precision of 5, but when the data is read and displayed in PandasTable, the rounding/precision set is not taken into effect.

**Comment by psraman3** [comment]
![image](https://user-images.githubusercontent.com/54652862/67171860-9984eb80-f3eb-11e9-8f53-78d0c5626535.png)

**Comment by psraman3** [comment]
Hi, @dmnfarrell , Thanks again. Following is the code I used, and it throws a Nameerror, and the precision display does not take in effect. I may be missing something here. Kindly help out. 
![image](https://user-images.githubusercontent.com/54652862/67171929-e4066800-f3eb-11e9-8a4c-61213c274449.png)

The error message is:
![image](https://user-images.githubusercontent.com/54652862/67171958-000a0980-f3ec-11e9-9755-4dd8cc30ead7.png)

**Comment by dmnfarrell** [comment]
You have an error message.  You need from . import config

**Comment by psraman3** [comment]
Hi, @dmnfarrell, after import config as below, the error message is gone.
![image](https://user-images.githubusercontent.com/54652862/67198211-1f775580-f431-11e9-9d39-6f261a4f967f.png)

But, still the precision is not set properly. I also tried to set the precision from GUI:
![image](https://user-images.githubusercontent.com/54652862/67198184-0bcbef00-f431-11e9-8610-fcb4be81737f.png)

**Comment by dmnfarrell** [comment]
It could be a windows issue. I'd have to test it. I use Linux.

**Comment by psraman3** [comment]
Ok , thanks. Waiting for your reply after Windows test. Meanwhile, just to reiterate, this precision was working fine if I read a CSV file to display in PandasTable. The problem occur when using Pandas df to display directly.

**Comment by psraman3** [comment]
Hi, it says its object type

**Comment by dmnfarrell** [comment]
Yes it will only work on float columns at the moment. Any column with text in it will be object.

**Comment by psraman3** [comment]
@dmnfarrell, Thanks. I converted the dtype of my df from object to float, and now it works fine. Thanks for the help...great job with PandasTable ....Thanks.
