### ISSUE TITLE
pandastable works with pandas 23.4 and not with later versions

### ISSUE THREAD

**Issue by gsudhanshu** [dmnfarrell/pandastable#154]
pandastable works with pandas 23.4. Kindly advise if I can install latest pandas version..

I have a dependency on pandastable

**Comment by dmnfarrell** [comment]
What versions does it not work with?

**Comment by gsudhanshu** [comment]
later versions

**Comment by gsudhanshu** [comment]
I am using python 2.7.16

**Comment by dmnfarrell** [comment]
Version 0.24.2 works for me on python 2.7.17.

**Comment by gsudhanshu** [comment]
Ok, noted
