### ISSUE TITLE
Import csv - how to set datatypes before import

### ISSUE THREAD

**Issue by nickrye** [dmnfarrell/pandastable#158]
While in import, I assumed that right-clicking on column headers and choosing data type would be reflected in the imported table, but it doesn't seem to be. In my case, trying to make an integer into str. Thanks.

**Comment by dmnfarrell** [comment]
No it's just a preview. I should disable any right click or editing on that table. You are best to import then make those changes.

**Comment by nickrye** [comment]
If you can't set the datatype before the import, setting it after import would be too late, wouldn't it? For example, if you had integer numbers with leading zeroes that you wanted to keep, the import would remove the leading zeroes and you couldn't get them back with a datatype setting after import I don't think.
Pandastable is a great tool! I haven't seen a better interactive table viewer/analyzer. Thanks for your work. Did you create it because there wasn't a good viewer out there?

**Comment by dmnfarrell** [comment]
Fair point. This could be solved with an option to interpret values with leading zeroes as strings in the dialog. That would probably be easier to implement. I'll take a look.
Thanks for your comments. This article might be of interest to you: https://decisionstats.com/2015/12/25/interview-damien-farrell-python-gui-dataexplore-python-rstats-pydata/

**Comment by nickrye** [comment]
That seems like a good solution. Thanks for considering. The article was interesting and answers my question.

**Comment by dmnfarrell** [comment]
You can now choose 'numbers as string' in the import dialog. It should allow leading zeroes to be kept. Note this will treat all numeric columns in the file as string, so you might need to convert them to number after import.

**Comment by nickrye** [comment]
I can only speak for myself, but I think the typical case would be that most numbers would be desired to be imported as they are, as float or int, and that only a few number fields would be desired as strings, such as postal codes. I was thinking your idea of leading zero identification and setting to str would have been more aligned with most needs.  That wouldn't help, of course, if the number field you want as str has no leading zeroes, but I would think a user would prefer to change the datatype of those few fields after import rather than change the datatype of many number fields back to number after import.
We are likely to include pandastable as the file viewer/analyzer for an environmental model we (USEPA) recently recoded in Python. Based on my searching, it seems to be the best tool for that purpose. I appreciate your time and effort, and I don't expect you to go out of your way to tailor it for our purposes.
Thanks!

**Comment by dmnfarrell** [comment]
I don't mind adding features if they have a some general use. But I often have to go for the simplest solution as in this case. Detecting leading zeroes in import for individual columns would be better but requires more extensive changes to the import code and dialog. Of course you could always write a plugin to do your own import. An alternative might be to allow display of fields with leading zeroes.

**Comment by nickrye** [comment]
Okay. Thanks again for your time and effort.

**Comment by dmnfarrell** [comment]
No problem. If I get time I'll look at this again.
