### ISSUE TITLE
Add commands to right-click menu

### ISSUE THREAD

**Issue by JT-101** [dmnfarrell/pandastable#160]
I'm trying to add a command to the right-click menu to "open excel" like that in the toolbar. It says in popupMenu() not to override the function, but I could not see how to add a command otherwise. I looked through the documentation, but couldn't find an example. Is there sample code for this somewhere or could you provide a brief overview?

Thanks for any help!

**Comment by dmnfarrell** [comment]
Yes you need to override that method. The documentation is not up to date for this. Here is a code snippet:

```
class MyTable(Table):
    """
      Custom table class inherits from Table.
      This overrides the right click menu.
     """
    def __init__(self, parent=None, app=None, **kwargs):
        Table.__init__(self, parent, **kwargs)
        #reference to parent app
        self.app = app
        return

    def popupMenu(self, event, rows=None, cols=None, outside=None):
        """Custom right click menu"""

        popupmenu = Menu(self, tearoff = 0)
        def popupFocusOut(event):
            popupmenu.unpost()
            popupmenu.add_command(label='Do function', command=self.app.myfunction)

        popupmenu.bind("<FocusOut>", popupFocusOut)
        popupmenu.focus_set()
        popupmenu.post(event.x_root, event.y_root)
        return popupmenu
```

**Comment by JT-101** [comment]
Thank you for the quick reply! Looks like this does what I need.

**Comment by david-c-wong** [comment]
The code above seems to replace the whole Popup menu by a simple menu having "Do function" option only (if I unindent the popupmenu.add_command(...) statement).

Would it be possible to *append* the command to the original popup menu so we are adding menu items rather than replacing menu items?

Thanks.

**Comment by dmnfarrell** [comment]
Maybe you could call the original popupMenu method and then append the item to the menu in your overriding function.

```python
def popupMenu(self, event, rows=None, cols=None, outside=None):
        """Custom right click menu"""

        popupmenu = Table.popupMenu(event)
        #popupmenu add_command here

        return popupmenu
```
