### ISSUE TITLE
pt.show() and changes in pandas 1.0

### ISSUE THREAD

**Issue by mpy20** [dmnfarrell/pandastable#166]
Hey,

Using  pt.show() I get an error after update to pandas 1.0.0:
  

>   File "C:\ProgramData\Anaconda3\lib\site-packages\pandastable\core.py", line 279, in show
    self.tablecolheader = ColumnHeader(self.parentframe, self, bg=self.colheadercolor)

>   File "C:\ProgramData\Anaconda3\lib\site-packages\pandastable\headers.py", line 56, in __init__

>   if util.check_multiindex(self.model.df.columns) == 1:

>   File "C:\ProgramData\Anaconda3\lib\site-packages\pandastable\util.py", line 58, in check_multiindex

>   if isinstance(index, pd.core.index.MultiIndex):

> AttributeError:`` module 'pandas.core' has no attribute 'index'

I guess it is due to the backwards incompatible changes in multiIndex.levels. Are you going to fix that?

Regards,
mpy

**Comment by dmnfarrell** [comment]
This has been fixed in the current code. I have yet to make a new release. If there are any other pandas 1.0 issues you can report them.

**Comment by mpy20** [comment]
Thanks for your answer. Sure I will do. Atm this is the main issue impacting most of my projects.
