### ISSUE TITLE
Sorting always uses first column in 0.12.2 (regression)

### ISSUE THREAD

**Issue by texoft** [dmnfarrell/pandastable#167]
Steps to reproduce:

1. Open dataframe/table with several columns
2. Click on column header to sort
3. Notice that table is always sorted using first column values regardless on what column header you click

Expected behavior (as in 0.12.1) is that table gets sorted based on column you clicked.

**Comment by dmnfarrell** [comment]
Thanks accidentally introduced this bug. This is fixed if you update.
