### ISSUE TITLE
setRowColors pandas warning

### ISSUE THREAD

**Issue by mpy20** [dmnfarrell/pandastable#168]
I am using table.setRowColors method for coloring rows depending on several rules. In case I hand over a list with row indices I get a future warning:

FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = getitem(key)

I guess this has to be fixed in the method in the future or am I doing something wrong?

Best regards.

**Comment by dmnfarrell** [comment]
It just means that your code could break or give the wrong result in a future version of pandas as the behaviour will change. I'd just use the recommended method if you want to be safe.

**Comment by mpy20** [comment]
Thanks for your reply. But isn't it a error that comes from "your" method? I just displaying and df with:

pt = pandastable.core.Table(rahmen, dataframe=df3, showtoolbar=False, showstatusbar=True, height=400, width=1500) #table with dataframe
pt.show()

and then calling the method with:
pt.setRowColors(rows=[rowlist], clr="#f00", cols="all")

where rowlist is a list type variable. How can I prevent that on my side? If I do not call your function the errors disapears.

Your help would be much appreciated.

**Comment by dmnfarrell** [comment]
Ok sorry didn't read that properly. I'll take a look at it. It is just a warning though, for now.

**Comment by mpy20** [comment]
Thank you. And yes, no problems for now, I just wanted to report that proir to any problems ;-) I am heavily using your package :-)
