### ISSUE TITLE
Python shell with DataExplore?

### ISSUE THREAD

**Issue by kmatt** [dmnfarrell/pandastable#17]
It is possible to work with a Python console and DataExplore? 

The idea would be to manipulate a Pandas dataframe and work with the results in DataExplore, much like the RStudio object viewer.

**Comment by dmnfarrell** [comment]
Yes it might be possible as indicated by thread below. I will mark this as an enhancement.

http://stackoverflow.com/questions/21811464/how-can-i-imbed-a-python-interpreter-frame-in-python-using-tkinter

**Comment by dmnfarrell** [comment]
This is now implemented using the ipython library. see https://github.com/dmnfarrell/pandastable/wiki/IPython-console-plugin
Note no tab completion yet but basics work.
