### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'as_matrix' when trying to calculate new column

### ISSUE THREAD

**Issue by ptarra** [dmnfarrell/pandastable#172]
This seems to be a problem with a deprecated method in Pandas. The documentation for version 0.25 says that the method is deprecated and [suggests using Dataframe.Values() instead ](https://pandas.pydata.org/pandas-docs/version/0.25.1/reference/api/pandas.DataFrame.as_matrix.html) However the documentation for .Values() [recomends using to_numpy().](https://pandas.pydata.org/pandas-docs/version/0.25.1/reference/api/pandas.DataFrame.as_matrix.html). 

I suggest the following patch:

> diff --git a/core.py b/core.py
> index 6496b99..e19535a 100644
> --- a/core.py
> +++ b/core.py
> @@ -1788,7 +1788,7 @@ class Table(Canvas):
>          #uses assignments to globals() - check this is ok
>          import numexpr as ne
>          for c in df:
> -            globals()[c] = df[c].as_matrix()
> +            globals()[c] = df[c].to_numpy()
>          a = ne.evaluate(ex)
>          return a

**Comment by dmnfarrell** [comment]
patched. thanks.
