### ISSUE TITLE
Cannot install plugins

### ISSUE THREAD

**Issue by CsatiZoltan** [dmnfarrell/pandastable#173]
When I click on Plugins -> Install Plugin and select any of the plugins in the [plugins directory](https://github.com/dmnfarrell/pandastable/tree/master/pandastable/plugins), I receive the following error:

```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/zoltan/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/zoltan/anaconda3/lib/python3.7/site-packages/pandastable/app.py", line 950, in installPlugin
    shtutil.copy(filename, self.pluginpath)
NameError: name 'shtutil' is not defined
```

I installed DataExplore using the snap package.

**Comment by dmnfarrell** [comment]
Plugins don't work from the snap I think.
If you need them I would remove the snap and install the latest version from github using pip if you can.
pip install -e git+https://github.com/dmnfarrell/pandastable.git#egg=pandastable

**Comment by CsatiZoltan** [comment]
OK, I executed `pip install -e git+https://github.com/dmnfarrell/pandastable.git#egg=pandastable`, but how can I start DataExplore? I tried `python -m dataexplore` but there is no such module.

**Comment by dmnfarrell** [comment]
There was a bug but install plugins is actually meant when you have the file in another folder outside the default one. It should load the ones in the plugin folder automatically. Are there any plugins in the menu?

**Comment by CsatiZoltan** [comment]
Yes, I have *Batch Process*, *Differential Expression*, *IPython Console*, *Batch File Rename* and *Factor Plots*. I wanted to install [*example.py*](https://github.com/dmnfarrell/pandastable/blob/master/pandastable/plugins/example.py) for curiosity.

**Comment by dmnfarrell** [comment]
Anything in the plugin folder will be loaded but for the example.py you have uncomment the line;

**Comment by Ittaimuller** [comment]
Hello. Im trying to install this plugin using install plugin or by adding it to the plugin folder but it doesnt show up. https://www.sciencedirect.com/science/article/pii/S0731708520313017#bib0140

its the elisa-tool plugin. 

im on a windows binary installation. 

Thanks.

**Comment by dmnfarrell** [comment]
This is a scientific paper so the authors should have made sure the plugin works before publishing. I'm guessing that they didn't test it with the standalone binary. It could be a bug. I'd have to check it out. Your best bet might be to install the program with pip instead.

**Comment by Ittaimuller** [comment]
Thank you for your response. I asked the authors for response as well.
In their paper they explicitly note to use the windows binary so seems
sloppy.

will try using pip install

**Comment by dmnfarrell** [comment]
It's confusing because they require that you unzip the elisa_tool_repo folder to the plugins folder also. Then that's imported in the plugin. That's not ideal. They should probably have provided their package on pip separately.
Anyway it still won't work for me when I do that as it says 
```
failed to load core_elisa_tool_plug plugin
No module named 'RegscorePy'
```
The problem with the binary is it won't give these error messages.
