### ISSUE TITLE
Certain numbers showing as scientific notation after calculation

### ISSUE THREAD

**Issue by arbitrager44** [dmnfarrell/pandastable#174]
I'm encountering a problem where a cell values are displaying as scientific notation. The code is very simple. After the user enters some number, two columns are subtracted from each other in `pandas`. For good measure, I used `round` to zero decimals. If I `print` the dataframe, I get the expected result. But in PT, it shows it as scientific notation. Hence I'm _assuming_ it is a PT issue, but open to counterclaims!

The problem doesn't happen universally with every possible combination, but it isn't just one cell.

Here are screenshots.

From PT:
![image](https://user-images.githubusercontent.com/46244905/82918129-4a370880-9f42-11ea-8727-58d947049b94.png)

Printing the df:
![image](https://user-images.githubusercontent.com/46244905/82918189-5c18ab80-9f42-11ea-933a-6d594a2b39ea.png)

**Comment by dmnfarrell** [comment]
I can't replicate that. What if you cast the new column as an object type instead of float.

**Comment by arbitrager44** [comment]
Yes that works! It is strange behavior and I was worried it was going to be hard to replicate. Thanks @dmnfarrell
