### ISSUE TITLE
Extending column size a lot

### ISSUE THREAD

**Issue by venkateshmicro98** [dmnfarrell/pandastable#176]
![image](https://user-images.githubusercontent.com/31404179/85007739-8d6b4c80-b179-11ea-91e6-11319648285d.png)

When column size is extended, after certain limit [in my case the window size] it is not rendering properly while scrolling using scrollbar.

This also results in making the entire table empty

**Comment by dmnfarrell** [comment]
I can't replicate this. I've added a line that might fix it though.
