### ISSUE TITLE
Can Table auto-fill a frame?

### ISSUE THREAD

**Issue by yucongo** [dmnfarrell/pandastable#179]
```python
import tkinter as tk
from pandastable import Table
import pandas as pd

df = pd.DataFrame({
    'A      ': [1,2,3,4,5,6,],
    'B': [1,1,2,2,3,3,],
    'C': [1,2,3,1,2,3,],
    # 'D': [1,1,1,2,2,2,],
})

root = tk.Tk()
root.title('PandasTable Example')

frame = tk.Frame(root)
frame.pack(fill='both', expand=True)

pt = Table(frame, dataframe=df)
pt.show()
root.mainloop()
```
Can I somehow make pt fill up frame in the snippet above? The pt Table above only fills part of frame.  

I know I can drag the column borders to enlarge the columns.  I checked the Table class but cant find a way to do that programmatically.

Thanks very much.

**Comment by dmnfarrell** [comment]
I guess you mean fit the columns to the width. There's no method for this. Though it wouldn't be hard to implement. You can also try pt.expandColumns(x) where x is the factor.

**Comment by yucongo** [comment]
pt.expandColumns(x) is good :thumbsup:. pt.columnwidths and pt.tablewidth can be usefull, too.
