### ISSUE TITLE
Error while importing from excel

### ISSUE THREAD

**Issue by evnb** [dmnfarrell/pandastable#181]
_(Using pandastable-0.12.2 with python 3.6 on Windows 10.)_
TypeError: read_excel() got an unexpected keyword argument `sheetname`

[According to StackOverflow user mjfwest](https://stackoverflow.com/q/57348149#comment111037026_57348149):
> The parameter `sheetname` was depreciated and then replaced with `sheet_name` in 2018. See [Github issue #20920](https://github.com/pandas-dev/pandas/issues/20920)

Hopefully this will be a quick and easy fix :)

**Comment by dmnfarrell** [comment]
This has already been fixed but isn't in the current release. You could install the version from github to get the most recent commit.

`pip install -e git+https://github.com/dmnfarrell/pandastable.git#egg=pandastable`
