### ISSUE TITLE
cannot use the Filter Rows -> Color filtered rows 

### ISSUE THREAD

**Issue by njcuk9999** [dmnfarrell/pandastable#183]
It crashes with the following error:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/cook/miniconda3/envs/apero-env/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/cook/miniconda3/envs/apero-env/lib/python3.7/site-packages/pandastable/dialogs.py", line 1471, in colorResult
    clr = self.table.getaColor('#dcf1fc')
AttributeError: 'Table' object has no attribute 'getaColor'
```

pandastable version is 0.12.2

Following it back I used the "Filter Rows" option in the right-click popup menu 

popupMenu --> "Filter Rows" -> self.queryBar --> QueryDialog 
--> QueryDialog.setup() --> self.colorResult --> self.table.getaColor

Problem is `self.table` (from `core.py` `Table` class ) does not have a method `getaColor`

In fact, as far as I can tell in this version there is no `getaColor` method/function anywhere in core.py

I fixed this mysel by adding my own Table class and use that instead:

```python
from pandastable import Table, dialogs

class MyTable(Table):
    def __init__(*args, **kwargs):
        Table.__init__(self, *args, **kwargs)

    def getaColor(self, oldcolor):
         return dialogs.pickColor(self, oldcolor)
```

I'm using `dialogs.pickColor` is the option wanted here (at least it works) but figured I'd flag this, so the required behavior is done.

Great package, by the way, I'm very impressed!

**Comment by dmnfarrell** [comment]
closing this. thanks for the comment
