### ISSUE TITLE
Cell values consisting of several lines overlap in table

### ISSUE THREAD

**Issue by choongyx** [dmnfarrell/pandastable#185]
Hi, 

I have a dataframe which I have imported from a csv to display as a table. One of the columns of the dataframe has values that contain several lines. The cell values overlap as shown in the image below. May I ask whether there is a way to fix this such that the values wrap or do not show if they exceed the width of the cell?

<img src="https://user-images.githubusercontent.com/39525563/93578805-59016980-f9d0-11ea-82c1-c1bab8dfc171.png" width="35%">

Thank you!

**Comment by dmnfarrell** [comment]
Values should always be truncated to fir the column width. There is no wrapping in cells though. Does your data contain hard returns? If so remove them and it should work.

**Comment by choongyx** [comment]
Yup it contains hard returns, thanks!
