### ISSUE TITLE
is there any way to integrate into Angular app? Thanks !

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [dmnfarrell/pandastable#186]
is there any way to integrate into Angular app? Thanks !

It would be nice if it has app integration in web app. Just for curious to know. THanks for your time :+1:

**Comment by dmnfarrell** [comment]
No this isn't possible with Tkinter to my knowledge.

**Comment by vijayakumarmariyappan** [comment]
@dmnfarrell  Thank for your feedback :+1:  and time :)
