### ISSUE TITLE
Color selected row

### ISSUE THREAD

**Issue by GreenX5** [dmnfarrell/pandastable#187]
When I click a row, I see the color of all cells of row change to red or gray. Can this be reversed using the Python method? For example, change the font color, get a border for the line, or something else? I really want to preserve the colors of the cells. Thanks!

**Comment by GreenX5** [comment]
I have now turned off the drawing of the rectangle for the line fully. Is it possible to turn off just filling the rectangle?

```
    def drawSelectedRow(self):
        return # switch off full
        self.delete('rowrect')
        row = self.currentrow
        x1,y1,x2,y2 = self.getCellCoords(row,0)
        x2 = self.tablewidth
        rect = self.create_rectangle(x1,y1,x2,y2,
                                  fill=self.rowselectedcolor,
                                  outline=self.rowselectedcolor,
                                  tag='rowrect')
        self.lower('rowrect')
        #self.lower('fillrect')
        self.lower('colorrect')
        self.rowheader.drawSelectedRows(self.currentrow)
        return
```

**Comment by dmnfarrell** [comment]
Can't you just omit the fill parameter when calling self.create_rectangle? I would generally advise people to implement their own class and override these methods rather than changing the core classes directly.

**Comment by GreenX5** [comment]
Yes thank you. This inhibits the filling.
`#fill=self.rowselectedcolor`
Can you tell me where I should look for your function create_rectangle? These are not typical attributes for mathplot rectangle and I cannot find the place of birth it.
Thanks for your great work! This is irreplaceable!

**Comment by dmnfarrell** [comment]
`create_rectangle` is a property of a tkinter canvas which this is inherited from. You can just override `drawSelectedRow`. Maybe that's what you are already doing?
