### ISSUE TITLE
dataexplore does not launch on Windows 10

### ISSUE THREAD

**Issue by jbiz25** [dmnfarrell/pandastable#188]
Hi,  

I am using Windows 10.  I installed pandastable into a venv.  It seemed to go fine.  But when I try to launch dataexplore from the command line with my venv activated, nothing happens.  I verified that there is indeed a dataexplore.exe in my venv's Scripts folder.  Even if I type dataexplore -h, nothing happens.  Any ideas?

**Comment by philsuess** [comment]
I have the same issue. pip install pandastable in a venv and the command does nothing.
