### ISSUE TITLE
Apply the sort not only the column but also on the graph

### ISSUE THREAD

**Issue by ThomasG77** [dmnfarrell/pandastable#19]
When I apply a sort on a column, I would like to see the graph changes also.

In my test, it keeps the original order. In my use case, I would prefer to see the sort also in the graph to get a better overview of the data distribution for my column.

**Comment by dmnfarrell** [comment]
Do you mean you want the plot to automatically update when a sort is done? Also this would only really apply to bar plots I assume since for scatter or other plots sort order would not be relevant.

**Comment by dmnfarrell** [comment]
By default now for bar plots the sort order will be reflected on the plot.
