### ISSUE TITLE
SetRowColors 'Table' object has no attribute 'setRowColors'

### ISSUE THREAD

**Issue by Mitaliushah** [dmnfarrell/pandastable#190]
f = Frame(window)
    f.grid(row=1, column=0, columnspan=50)

    pt = Table(f, dataframe=aj, showtoolbar=False, showstatusbar=True, height=400, width=400, cols=50)
    pt.show()
    pt.setRowColors(rows=1, clr='#FF0000', cols=None)

I get the error 'Table' object has no attribute 'setRowColors'
I'm using python 3.7 and used pip to install pandastable

**Comment by dmnfarrell** [comment]
It should work if you use `cols='all'`. Probably that should be the default value. Check the API docs for usage.
