### ISSUE TITLE
is there a docker implementation?

### ISSUE THREAD

**Issue by davecampbell** [dmnfarrell/pandastable#196]
i'm having trouble teasing out all the dependencies and installation instructions for OS/X.

is there a docker / docker-hub implementation that i can use to simply test / review this amazing looking toolset?

thanks.

**Comment by dmnfarrell** [comment]
No sorry I've never looked into docker. I don't have access to a mac so have never been able to test it on OSX. I assume you tried just `pip install pandastable`?
