### ISSUE TITLE
Setting colour of cell in dataframe

### ISSUE THREAD

**Issue by cleehl** [dmnfarrell/pandastable#197]
I'm not sure if I'm following the example correctly but for am unable to set the cell's row colour and keep getting error colour hexa code cannot be converted to string? - "ValueError: could not convert string to float: '#3776ab'"

How should I modify the code below to change the colour of the particular row/column cell?

import pandas as pd
import tkinter as tk
import sqlite3
from pandastable import Table

connection = sqlite3.connect(database_filepath)
sql_query = 'SELECT * FROM test_table'
df = pd.read_sql_query(sql_query, connection)

window = tk.Tk()
panel_frame = tk.Frame(window)
pt = Table(panel_frame, dataframe=df, showtoolbar=True, showstatusbar=True)

pt.setRowColors(rows=2, clr='#3776ab', cols=[3,5])
pt.redraw()
pt.show()

panel_frame.grid(row=1, column=1, sticky='nswe')
window.mainloop()

**Comment by GrannySmith21** [comment]
Hello,

For some reasons, the row attribute of setRowColors must be a list. So pt.setRowColors(rows=[2], clr='#3776ab', cols=[3,5]) should work.
