### ISSUE TITLE
Update cell while filter up

### ISSUE THREAD

**Issue by alexgg94** [dmnfarrell/pandastable#198]
Hi,

I have loaded a really large dataFrame and I would like to filter rows, and then, to manually change some cell values by clicking on them and editing the new value.

I've realized that this feature works when there is no filter applied, but once a filter is up, the cell won't change it's value after editing it.

Is there any way to accomplish this?

Thanks

**Comment by dmnfarrell** [comment]
No you can't edit filtered tables at the moment. The filtered table is a copy of the original so when you edit the changes are not reflected. It should really show a message saying so. You might be better off just copying the filtered one to another table then merging it back with the original?

**Comment by alexgg94** [comment]
I am really interested in this edit while filter up feature. 

One thing I didn't mention is that I'm only going to update columns which I'm not using for the filtering process.

What would be the best approach to implement it myself?

**Comment by dmnfarrell** [comment]
Its tricky since you are looking at a partial view of the real table. You'd have to be able to get the index of the cell being edited in the filtered table and use that to update the underlying table. It would require a separate method for editing if self.filtered is True than the usual one. The edit function is in the tablemodel.

**Comment by alexgg94** [comment]
Is there any way to access this filtered dataframe from the _def handleEntryMenu(self, *args)_ function?

**Comment by dmnfarrell** [comment]
When the table is filtered it overwrites the current table with the filtered one and displays it. The actual table is kept in `self.dataframe` which is restored after filtering. So actually when you edit it can update the filtered table as normal. It's just that when you stop filtering the old table is restored.
So you should overrride `handleCellEntry`, you can see where it checks for filtering. If filtered it just ignores the edit to avoid letting the user think it's working.

```python
def handleCellEntry(self, row, col):
    """Callback for cell entry"""

    value = self.cellentryvar.get()
    if self.filtered == 1:
        df = self.dataframe
    else:
        df = None
    self.model.setValueAt(value,row,col,df=df)

    self.drawText(row, col, value, align=self.align)
    self.delete('entry')
    self.gotonextCell()
    return
```

**Comment by alexgg94** [comment]
Thanks for the help. I've modified _handleCellEntry_ to update both original and filtered dataframe whenever the filter is up. 

Closing issue.

Greetings.

**Comment by dmnfarrell** [comment]
Does this work in all situations? Could you post your code here. I may be able to integrate your changes.

**Comment by alexgg94** [comment]
I don't really know if it fits all situations... I've also ended up modifying _def handleEntryMenu(self, *args)_ to handle multiple cell edition by drop down menu.

Here is the code

```
        value = self.dropvar.get()
        self.delete('entry')
        rows = self.getSelectedRows()
        col = self.currentcol
       
        for index in rows.index.values:
            row = self.model.df.index.get_loc(index)

            self.model.setValueAt(value,row,col)

            if(self.filtered):
                self.dataframe.loc[(self.dataframe.index == index), 'res'] = value

            self.drawText(row, col, value, align=self.align)
```

**res** column is the only column editable, so I just go and set it to the value I need. Again, I think that my implementation is not going to fit all general cases, but hope it helps :)

**Comment by Chewbathra** [comment]
Hello,

If someone needs to update the value in the cell while the filter is on, here's what I did:

class OwnTable(Table):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def handleCellEntry(self, row, col):
        """Callback for cell entry"""
        if self.filtered:
            filtered_df = self.model.df
            value = self.cellentryvar.get()
            self.model.setValueAt(value, row, col, df=filtered_df)
            row = filtered_df.iloc[row].name
            super().handleCellEntry(row, col)
            super().redraw()  # Need to redraw only if on filter mode
        else:
            super().handleCellEntry(row, col)

It updates the value in the copied filtered dataframe as well as in the base dataframe and redraws the view.
The only possible update (or not, I don't know) is if you update the column on which you made the filter, the latter remains displayed even if it no longer corresponds to the filter.

It seems to work on all situations.
