### ISSUE TITLE
whish 2016

### ISSUE THREAD

**Issue by stonebig** [dmnfarrell/pandastable#20]
By order of (complex) whish:
- match/do-better-than user simplicity of "excel slicers",
- scale over 1 000 000 rows,
- update goals and/or dates on your github milestones,
- add "ttk" in your setup.py keywords.

**Comment by dmnfarrell** [comment]
Can you explain what you mean by the first two in more detail? The table will scale up to >1 million rows but it will take time to load a large dataframe or csv file. A progress bar is needed for that.
I can add ttk" to the setup.py file.

**Comment by stonebig** [comment]
The first two are Ease-of-use problems I encounter when browsing (my sort of) Dataframes with the Python stack.

- no (Excel-like) Slicers:
 - a slicer is a multi-selectable list of uniques values present in a given column:
  - sorted by "shown" in current sub-selection of dataframe, then "hidden" 
  - sub-sorted in alphabetical order
 - several Slicers can be shown to user to sub-select a given dataframe,
 - when you click on one slicer choice, the other slicers are re-draw to show remaining 'visible' values first,
 - for a Dataframe of sales of a Portfolio of Product with a  "Unit Weight" slicer, the user can select his own definition of "small units" and see immediately the effect on the Dataframe (in its 'resume' form, a Pivot Table or a graphic in Excel case)

- browsing over 1 000 000+ rows
 -  400 000 rows is a limit at which Excel becomes unusable (too slow),
 -  in my personnal experiment, loading a big Dataframe in a Graphical Python Library becomes unusable at much lower than 400 000 rows, so managing 1 000 000 rows mean being able not to load them all but only a window (a complex machinery).

The "ttk" tag is to help increase your visibility on Pypi.
