### ISSUE TITLE
Error: AttributeError: 'Table' object has no attribute 'currwidth'

### ISSUE THREAD

**Issue by javadze1379** [dmnfarrell/pandastable#201]
file: D:\pandastable\pandastable\core.py
Error line: 320
Error code: if self.currwidth !=self.parentframe.winfo_width() or \
Error Message: AttributeError: 'Table' object has no attribute 'currwidth'

Solution:
Initialize  currwidth , currheight before line 304 to don't have issue for calling self.resized function

**Comment by dmnfarrell** [comment]
I can't replicate this but added a line to check if currwidth exists
