### ISSUE TITLE
Table is not following grid

### ISSUE THREAD

**Issue by mjessa12** [dmnfarrell/pandastable#204]
I have successfully imported my DF into my program but im trying to add a row of text above the DF but the table is not obeying the grid.

Does anyone know how to fix this?

```
def display_df_frame(container, df):
    frame = ttk.Frame(container)
    #
    ttk.Label(frame, text='Top Entries').grid(column=0, row=0)
    pt = Table(frame, dataframe=df, height=400, width=300, showstatusbar=False)
    pt.grid(column=0, row=1)
    pt.show()

    return frame
```

**Comment by dmnfarrell** [comment]
You can't grid the widget directly as it is already put into the parent frame using the `show` method. If you want to add it to a grid put the enclosing frame in the grid instead.
