### ISSUE TITLE
AttributeError in TableMode..getColumnData()

### ISSUE THREAD

**Issue by GBR-613** [dmnfarrell/pandastable#205]
Create a table and set the data. Then try to run the following:
`val_list = my_table.model.getColumnData(columnIndex=0)`

Result:
```
...
  File "c:\Programs\Python37\lib\site-packages\pandastable\data.py", line 309, in getColumnData
    if columnIndex != None and columnIndex < len(self.columnNames):
AttributeError: 'TableModel' object has no attribute 'columnNames'
```

**Comment by dmnfarrell** [comment]
Don't use this method. If you want access to the column data just use `table.model.df.columns[idx]` instead.

**Comment by GBR-613** [comment]
Sure the workaround is available, but why to keep it so?  I think it is very easy to fix; if not - why to ever keep this method?

**Comment by dmnfarrell** [comment]
This method is now removed. It was written for something else and no longer needed but I forgot to remove it. I think using df.columns is the most direct method. Not sure how it is a workaround?
