### ISSUE TITLE
Inconsistency between getSelectedRow() and getSelectedRows()

### ISSUE THREAD

**Issue by GBR-613** [dmnfarrell/pandastable#206]
I would expect similarly named methods to have similar behavior.
However the former returns the row number and the latter returns the rows content.
I believe getSelectedRow() should return the selected row content and the selected row index should be returned by another function, getSelectedRowNumber() or getSelectedRowIndex()
Alternatively, rename getSelectedRows() into getSelectedRowsContent()

**Comment by dmnfarrell** [comment]
Fair enough. I renamed  `getSelectedRows` to  `getSelectedRowData` as it's not really used anyway.
