### ISSUE TITLE
how to run on linux?

### ISSUE THREAD

**Issue by nbecker** [dmnfarrell/pandastable#21]
Installing as 
pip3 --user pandastable

There is no executable installed (into e.g., .local/bin).   How is the app started?

**Comment by dmnfarrell** [comment]
The command is pip3 install pandastable. This assumes you have pip installed? If not you can use your distributions package manager to install it.
It should install an executable called 'dataexplore' in your path.

**Comment by dacoex** [comment]
it seem that it runs exclusively with python3 on Ubuntu 14.04

**Comment by dmnfarrell** [comment]
yes it only works with python 3.

**Comment by dmnfarrell** [comment]
FYI this library now works with python 2.7
