### ISSUE TITLE
Plot function is not working on Mac 

### ISSUE THREAD

**Issue by Anassoumi** [dmnfarrell/pandastable#215]
I have tried to download a set of data but it doesn't seem to plot anything ...

**Comment by dmnfarrell** [comment]
Did you see an error message?

**Comment by dmnfarrell** [comment]
Try this now.

**Comment by Anassoumi** [comment]
Yes I believe that there is an issue in the plotting.py file related to the parent package [Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Anassoumi** [comment]
It’s working, thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
