### ISSUE TITLE
Having problem setting default colors correctly.

### ISSUE THREAD

**Issue by fishbacp** [dmnfarrell/pandastable#216]
This is a question and not really an issue, and I apologize if this is the incorrect place to post it. My simple example looks like the following, where I've already created my root window. I'm putting the table in a frame, which in turn needs to be placed in a Toplevel. I've experimented with a few of the default values in my Table instance.

data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])

table_window = Toplevel()
table_frame = Frame(table_window)
table_frame.pack()
pt = Table(table_frame,dataframe=df)

pt.textcolor = 'blue' 
pt.cellbackgr='white'
pt.colheadercolor='gray'
pt.rowheadercolor='gray'
pt.boxoutlinecolor='black'
pt.show()

<img width="594" alt="image" src="https://user-images.githubusercontent.com/40703653/163858058-071150c9-801e-4a33-af59-d3add2fa4a4f.png">

For some reason, I don't see why the row and column header backgrounds aren't the same shade of gray. Also, which values store the row and column header font colors? (Shown here as white for columns and black for rows.)

BTW, this is a great package, and I'm really glad I found it!

**Comment by dmnfarrell** [comment]
Thanks.
The rowheader color wasn't changeable at all. I've updated it a bit so you now set those attributes on the headers directly. (Don't use rowheadercolor or colheadercolor).
```
table.rowheader.bgcolor = 'orange'
table.colheader.bgcolor = 'lightgreen'
table.colheader.textcolor = 'black'
```
You'll have to be using the latest version from github to see this change.
