### ISSUE TITLE
table.setRowColors()  not working as expected

### ISSUE THREAD

**Issue by dkwdaft** [dmnfarrell/pandastable#219]
hi ,
I'm currently trying to write a function in my application that will colour  the row with a certain word located in it. I am trying to use the table.setRowColors()  method to do this. I'm following the documentation located [here](https://pandastable.readthedocs.io/en/latest/examples.html#table-coloring)   to do this. I currently have this code:
 `df = pt.model.df
    breakrows = df.index[df['Episode'] == "Break"].tolist()
    for row in breakrows:
        pt.setRowColors(row, color_code[1]) #, color_code[1] = hex colour code
        pt.redraw()
`
However, it seems to be only colouring in one cell within the selected row and is interpreted differently on Mac compared to Linux. How can I make it colour  the entire row? Also it is only showing the colour once it has been selected and deselected but the colour doesn't show when cell is selected. Below are some screenshots
linux screenshot
![Screenshot from 2022-05-06 12-54-40](https://user-images.githubusercontent.com/31158132/167130433-912b6804-c966-4e47-b2e4-b8bc7138f5bf.png)
Mac screenshot 
![Screenshot 2022-05-06 at 13 31 05](https://user-images.githubusercontent.com/31158132/167131809-b82017b7-5a8d-4782-94a9-27c895d66e0a.png)

**Comment by dkwdaft** [comment]
I managed to get it sorted via the API reference  docs can I suggest that for each example you link back to the API reference for the functions that are used ?

**Comment by dmnfarrell** [comment]
Ok thanks, I'll try to do that.
