### ISSUE TITLE
Copy and Paste Data From Excel 

### ISSUE THREAD

**Issue by nira123** [dmnfarrell/pandastable#226]
First time inquiry, please bare with me.
Is it possible to directly copy and paste data table from excel to pandastable?
I noticed it is working other way around(can copy and paste from pandastable to excel) 
Thanks

**Comment by dmnfarrell** [comment]
No you can't though I could probably add it if needed. You can do it in tablexplore.

**Comment by nira123** [comment]
Thank you for your reply Damien. I am using Pandastable for developing another tool. 
It would be great if you could make it possible.
Could you please kindly add that feature if possible.

**Comment by nira123** [comment]
Answer given in following tab is working for copying data from excel:
https://stackoverflow.com/questions/62700469/tkinter-spreadsheet-data-entry
Is it possible to bind this code with Ctrl+V in Pandastable  ?

**Comment by dmnfarrell** [comment]
This was actually there but only from the toolbar. You can now paste from the clipboard using ctrl-v or the right click menu. This will overwrite the table and won't paste into specific cells though. ctrl-z will undo last change only. If you want custom functionality you can always override the `paste` method.

**Comment by nira123** [comment]
Thanks Damien. 
I tried upgrading Pandastable. 
Copy and paste from excel to pandastable is still not working from my end.

**Comment by dmnfarrell** [comment]
This works for me on windows. Are you sure you upgraded?

**Comment by nira123** [comment]
Hmm. Thanks a lot Damien.
Not sure why it is not working for me. 
I am using following code in the answer at the moment: 
https://stackoverflow.com/questions/62700469/tkinter-spreadsheet-data-entry
