### ISSUE TITLE
Disable editing  a Specific Column 

### ISSUE THREAD

**Issue by nira123** [dmnfarrell/pandastable#227]
Hi Damien,
Just wondering whether it is possible to  disable editing  a Specific Column in a pandastable , if so how. 
Thanks.

**Comment by dmnfarrell** [comment]
No there is just one global editable variable. You could subclass the `drawCellEntry` method and check the current col against a list of columns you want to be non/editable.

**Comment by nira123** [comment]
I will try Damien,.
Thanks again!
