### ISSUE TITLE
Overriding Bind keys and mouse clicks

### ISSUE THREAD

**Issue by nira123** [dmnfarrell/pandastable#228]
Hi Damien,
Hope you are well. Could you please provide an example how event keys in [doBindings function](https://pandastable.readthedocs.io/en/latest/_modules/pandastable/core.html#Table.doBindings) can be overriden. 
For example, if I need to override the Delete key(bind) to delete the selected row instead of clear Data of selected cell for following example. 

```
import tkinter as tk
from pandastable import Table
import pandas as pd

df = pd.DataFrame({
    'A': [1,2,3,4,5,6,],
    'B': [1,1,2,2,3,3,],
})

root = tk.Tk()
root.title('PandasTable Example')

frame = tk.Frame(root)
frame.pack(fill='both', expand=True)

pt = Table(frame, dataframe=df)
pt.show()

root.mainloop()
```

Many thanks.

**Comment by nira123** [comment]
got that I think 
pt.bind("<Delete>", pt.deleteRow)  right ?

**Comment by dmnfarrell** [comment]
You may not even need to override the method. You could just call the bind function after the table has been created.
e.g.: `pt.bind("<Delete>", pt.deleteRow)`
For greater control you usually subclass though.

**Comment by nira123** [comment]
Thanks a lot Damien!
