### ISSUE TITLE
Make compatible with Python 2

### ISSUE THREAD

**Issue by inkenbrandt** [dmnfarrell/pandastable#24]
Modify tkinter dependencies to work with either version of python.  Most scientific python users and GIS platforms are still using python 2.  Cross compatibility would be awesome.  Maybe merge this library with your tkintertable app or add Pandas functionality to tkintertable?

**Comment by dmnfarrell** [comment]
Yes I'll have to look into python 2 compatibility and probably should have done it at the outset. I will give this a go for the next release.
Not likely I can add pandastable stuff to the old library though since the old one doesn't use dataframes at all.

**Comment by inkenbrandt** [comment]
By the way, your dataExplore app is really cool!  I can see a lot of uses for it and I think there a lot of scientists who would apply it.  I would love to contribute to it.  I just have to learn more tkinter and Python 3.  I was trying to find synonymous tkinter libraries for Python 2 to help you improve the cross-compatibility, but I couldn't.  Thank you for taking my issue seriously.

**Comment by dmnfarrell** [comment]
Thanks for the feedback. I'd say there are plenty of avenues for contribution in the form of plugins for sure. I did not develop this with GIS applications in mind but I can see lots of ways it might be useful even if just for the plotting functions. If you want to make a plugin or some other feature let me know.
Things seem to work in python 2.7 now so I will upload a new version to pypi shortly. I thought it would be a lot harder to make it compatible to be honest so lucky you asked for it!

**Comment by inkenbrandt** [comment]
I would love to contribute to the plugins!
