### ISSUE TITLE
Easy: Issue with Thousands Negative Number Formatting in PandasTable Module

### ISSUE THREAD

**Issue by i-balash** [dmnfarrell/pandastable#240]
I've encountered an issue in the pandastable module when using the "show" function in tkinter to display a table. When I select the "thousand separator" option, the float values are correctly separated for positive values. However, I've noticed that negative values, which are denoted by a "-" at the beginning, are displayed in scientific notation (and not with the correct thousandseparator).

It would be greatly appreciated if the formatting for negative values could be quickly fixed. This would greatly improve the usability and consistency of the module. Thank you!

**Comment by i-balash** [comment]
@dmnfarrell is it possible to fix this?

**Comment by dmnfarrell** [comment]
Long delay but this bug should be fixed. Please check.

**Comment by i-balash** [comment]
> Long delay but this bug should be fixed. Please check.

Thank you! What exactly should I check? There is no branch or PR associated to this ticket, and I am running the actual version of pandastable in pypi (0.13.1).

**Comment by i-balash** [comment]
actually it doesn't run at all after updating as described in the readme, when I try to open a table with this exception:

TypeError: infer_objects() got an unexpected keyword argument 'copy'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\i-balash\.pyenv\pyenv-win\versions\3.9.12\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\users\i-balash\onedrive\github\sec13f-analysetool\myenv\src\pandastable\pandastable\core.py", line 344, in resized
    self.redrawVisible()
  File "c:\users\i-balash\onedrive\github\sec13f-analysetool\myenv\src\pandastable\pandastable\core.py", line 486, in redrawVisible
    coldata = coldata.infer_objects(copy=False).fillna('')

**Comment by i-balash** [comment]
Yeah it works now!! Thanks a lot! The solution was to update the loading of the pkl from pandas instead of pickle.

![image](https://github.com/dmnfarrell/pandastable/assets/93594837/5f11f1a7-16ae-44dc-9c37-b26eb28e811a)

**Comment by dmnfarrell** [comment]
so it won't work for you with pandas version >2?

**Comment by i-balash** [comment]
> so it won't work for you with pandas version >2?

it works with pandas version > 2 with 

`dfs_dict = pd.read_pickle(dict_file_path)`

instead of

`pickle.dump(dfs_dict, file)` (this works only with pandas < 2)

As far I understood pandas > 2 is needed for the comming new release of pandastable, correct?

**Comment by i-balash** [comment]
Issue can be closed.

**Comment by dmnfarrell** [comment]
A fairly recent version of pandas should work, but <2 is not recommended. Thanks.
