### ISSUE TITLE
Error when install "writeByte not implemented"

### ISSUE THREAD

**Issue by hazardary** [dmnfarrell/pandastable#244]
Hi,
I encountered error when I install. Can you help to fix this?

Obtaining pandastable from git+https://github.com/dmnfarrell/pandastable.git#egg=pandastable
  Cloning https://github.com/dmnfarrell/pandastable.git to ./src/pandastable
  Running command git clone --quiet https://github.com/dmnfarrell/pandastable.git /home/hezhy/src/pandastable
  Resolved https://github.com/dmnfarrell/pandastable.git to commit 96a46c35e12023bdf8c81be21c9c0297f7677d67
  Preparing metadata (setup.py) ... done
INFO: Choosing GraalPy tested version 3.3.2 for matplotlib>=3.0
Traceback (most recent call last):
  File "<module>", line 266, in run
  File "<module>", line 381, in resolve
  File "<module>", line 138, in _add_to_criteria
  File "<module>", line 155, in __bool__
  File "<module>", line 557, in wrapper
  File "<module>", line 557, in wrapper
  File "<module>", line 812, in generate
  File "<module>", line 601, in stream
  File "<module>", line 529, in read
  File "<module>", line 481, in _fp_read
  File "<module>", line 89, in read
  File "<module>", line 28, in dumps
  File "<module>", line 755, in _pack
  File "<module>", line 964, in _pack_map_pairs
writeByte not implemented
Traceback (most recent call last):
  File "<module>", line 266, in run
  File "<module>", line 381, in resolve
  File "<module>", line 138, in _add_to_criteria
  File "<module>", line 155, in __bool__
  File "<module>", line 557, in wrapper
  File "<module>", line 557, in wrapper
  File "<module>", line 812, in generate
  File "<module>", line 601, in stream
  File "<module>", line 529, in read
  File "<module>", line 481, in _fp_read
  File "<module>", line 89, in read
  File "<module>", line 28, in dumps
  File "<module>", line 755, in _pack
  File "<module>", line 964, in _pack_map_pairs
writeByte not implemented
Traceback (most recent call last):
  File "<module>", line 266, in run
  File "<module>", line 381, in resolve
  File "<module>", line 138, in _add_to_criteria
  File "<module>", line 155, in __bool__
  File "<module>", line 557, in wrapper
  File "<module>", line 557, in wrapper
  File "<module>", line 812, in generate
  File "<module>", line 601, in stream
  File "<module>", line 529, in read
  File "<module>", line 481, in _fp_read
  File "<module>", line 89, in read
  File "<module>", line 28, in dumps
  File "<module>", line 755, in _pack
  File "<module>", line 964, in _pack_map_pairs
com.oracle.truffle.api.CompilerDirectives$ShouldNotReachHere: writeByte not implemented

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
alabaster                 0.7.12             pyhd3eb1b0_0
appdirs                   1.4.4              pyhd3eb1b0_0
arrow                     1.2.3            py38h06a4308_1
astroid                   2.14.2           py38h06a4308_0
asttokens                 2.0.5              pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     22.1.0           py38h06a4308_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.11.0           py38h06a4308_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.12.2           py38h06a4308_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     23.3.0           py38h06a4308_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
bottleneck                1.3.5            py38h7deecbd_0
brotli                    1.0.9                h5eee18b_7
brotli-bin                1.0.9                h5eee18b_7
brotlipy                  0.7.0           py38h27cfd23_1003
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.08.22           h06a4308_0
certifi                   2023.7.22        py38h06a4308_0
cffi                      1.15.1           py38h5eee18b_3
chardet                   4.0.0           py38h06a4308_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4            py38h06a4308_0
cloudpickle               2.2.1            py38h06a4308_0
colorama                  0.4.6            py38h06a4308_0
comm                      0.1.2            py38h06a4308_0
contourpy                 1.0.5            py38hdb19cb5_0
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              41.0.3           py38hdda0065_0
curl                      8.1.2                h409715c_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0
cyrus-sasl                2.1.28               h52b45da_1
dbus                      1.13.18              hb2f20db_0
debugpy                   1.6.7            py38h6a678d5_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.7            py38h06a4308_0
docstring-to-markdown     0.11             py38h06a4308_0
docutils                  0.18.1           py38h06a4308_3
entrypoints               0.4              py38h06a4308_0
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.5.0                h6a678d5_0
flake8                    6.0.0            py38h06a4308_0
fontconfig                2.14.1               h4c34cd2_2
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               h4a9f257_0
giflib                    5.2.1                h5eee18b_3
glib                      2.69.1               he621ea3_2
graalpy                   22.3.0          0_graalvm_native    conda-forge
gst-plugins-base          1.14.1               h6a678d5_1
gstreamer                 1.14.1               h5eee18b_1
icu                       58.2                 he6710b0_3
idna                      3.4              py38h06a4308_0
imagesize                 1.4.1            py38h06a4308_0
importlib-metadata        6.0.0            py38h06a4308_0
importlib_metadata        6.0.0                hd3eb1b0_0
importlib_resources       5.2.0              pyhd3eb1b0_1
inflection                0.5.1            py38h06a4308_0
intel-openmp              2023.1.0         hdb19cb5_46305
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.25.0           py38h2f386ee_0
ipython                   8.12.2           py38h06a4308_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
jaraco.classes            3.2.1              pyhd3eb1b0_0
jedi                      0.18.1           py38h06a4308_1
jeepney                   0.7.1              pyhd3eb1b0_0
jellyfish                 0.9.0            py38h7f8727e_0
jinja2                    3.1.2            py38h06a4308_0
jinja2-time               0.2.0              pyhd3eb1b0_3
joblib                    1.2.0            py38h06a4308_0
jpeg                      9e                   h5eee18b_1
jsonschema                4.17.3           py38h06a4308_0
jupyter_client            8.1.0            py38h06a4308_0
jupyter_core              5.3.0            py38h06a4308_0
jupyterlab_pygments       0.1.2                      py_0
keyring                   23.13.1          py38h06a4308_0
kiwisolver                1.4.4            py38h6a678d5_0
krb5                      1.20.1               h143b758_1
lazy-object-proxy         1.6.0            py38h27cfd23_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libbrotlicommon           1.0.9                h5eee18b_7
libbrotlidec              1.0.9                h5eee18b_7
libbrotlienc              1.0.9                h5eee18b_7
libclang                  14.0.6          default_hc6dbbc7_1
libclang13                14.0.6          default_he11475f_1
libcups                   2.4.2                h2d74bed_1
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.17                 h5eee18b_0
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hdbd6064_1
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 13.2.0               h807b86a_1    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libllvm14                 14.0.6               hdb19cb5_3
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libpng                    1.6.39               h5eee18b_0
libpq                     12.15                hdbd6064_1
libsodium                 1.0.18               h7b6447c_0
libspatialindex           1.9.3                h2531618_0
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_1    conda-forge
libtiff                   4.5.1                h6a678d5_0
libuuid                   1.41.5               h5eee18b_0
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
libxcb                    1.15                 h7f8727e_0
libxkbcommon              1.0.1                h5eee18b_1
libxml2                   2.10.4               hcbfbd50_0
libxslt                   1.1.37               h2085143_0
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               16.0.6               h4dfa4b3_0    conda-forge
lxml                      4.9.2            py38h5eee18b_0
lz4-c                     1.9.4                h6a678d5_0
markupsafe                2.1.1            py38h7f8727e_0
matplotlib                3.6.2            py38h06a4308_0
matplotlib-base           3.6.2            py38h945d387_0
matplotlib-inline         0.1.6            py38h06a4308_0
mccabe                    0.7.0              pyhd3eb1b0_0
mistune                   0.8.4           py38h7b6447c_1000
mkl                       2023.1.0         h213fc3f_46343
mkl-service               2.4.0            py38h5eee18b_1
mkl_fft                   1.3.6            py38h417a72b_1
mkl_random                1.2.2            py38h417a72b_1
more-itertools            8.12.0             pyhd3eb1b0_0
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3            py38h06a4308_1
mysql                     5.7.24               h721c034_2
nbclient                  0.5.13           py38h06a4308_0
nbconvert                 6.5.4            py38h06a4308_0
nbformat                  5.9.2            py38h06a4308_0
ncurses                   6.4                  h6a678d5_0
nest-asyncio              1.5.6            py38h06a4308_0
nspr                      4.35                 h6a678d5_0
nss                       3.89.1               h6a678d5_0
numexpr                   2.8.4            py38hc78ab66_1
numpy                     1.24.3           py38hf6e8229_1
numpy-base                1.24.3           py38h060ed82_1
numpydoc                  1.5.0            py38h06a4308_0
openssl                   3.1.2                hd590300_0    conda-forge
packaging                 23.1             py38h06a4308_0
pandas                    2.0.3            py38h1128e8f_0
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
patch                     2.7.6             h7f98852_1002    conda-forge
pathspec                  0.10.3           py38h06a4308_0
patsy                     0.5.3            py38h06a4308_0
pcre                      8.45                 h295c915_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.3.0            py38hace64e9_1
pip                       23.2.1           py38h06a4308_0
pkgutil-resolve-name      1.3.10           py38h06a4308_0
platformdirs              3.10.0           py38h06a4308_0
pluggy                    1.0.0            py38h06a4308_1
ply                       3.11                     py38_0
pooch                     1.4.0              pyhd3eb1b0_0
poyo                      0.5.0              pyhd3eb1b0_0
prompt-toolkit            3.0.36           py38h06a4308_0
psutil                    5.9.0            py38h5eee18b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
pycodestyle               2.10.0           py38h06a4308_0
pycparser                 2.21               pyhd3eb1b0_0
pydocstyle                6.3.0            py38h06a4308_0
pyflakes                  3.0.1            py38h06a4308_0
pygments                  2.15.1           py38h06a4308_1
pylint                    2.16.2           py38h06a4308_0
pylint-venv               2.3.0            py38h06a4308_0
pyls-spyder               0.4.0              pyhd3eb1b0_0
pyopenssl                 23.2.0           py38h06a4308_0
pyparsing                 3.0.9            py38h06a4308_0
pyqt                      5.15.7           py38h6a678d5_1
pyqt5-sip                 12.11.0          py38h6a678d5_1
pyqtwebengine             5.15.7           py38h6a678d5_1
pyrsistent                0.18.0           py38heee7806_0
pysocks                   1.7.1            py38h06a4308_0
python                    3.8.5           0_native223_graalpy    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py38h06a4308_0
python-lsp-black          1.2.1            py38h06a4308_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.7.2            py38h06a4308_0
python-slugify            5.0.2              pyhd3eb1b0_0
python-tzdata             2023.3             pyhd3eb1b0_0
python_abi                3.8             3_graalpy223_38_native    conda-forge
pytoolconfig              1.2.5            py38h06a4308_1
pytz                      2022.7           py38h06a4308_0
pyxdg                     0.27               pyhd3eb1b0_0
pyyaml                    6.0              py38h5eee18b_1
pyzmq                     25.1.0           py38h6a678d5_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.2.2            py38h06a4308_0
qt-main                   5.15.2               h7358343_9
qt-webengine              5.15.9               h9ab4d14_7
qtawesome                 1.2.2            py38h06a4308_0
qtconsole                 5.4.2            py38h06a4308_0
qtpy                      2.2.0            py38h06a4308_0
qtwebkit                  5.212                h3fafdc1_5
readline                  8.2                  h5eee18b_0
requests                  2.31.0           py38h06a4308_0
rope                      1.7.0            py38h06a4308_0
rtree                     1.0.1            py38h06a4308_0
scikit-learn              1.3.0            py38h1128e8f_0
scipy                     1.10.1           py38hf6e8229_1
seaborn                   0.12.2           py38h06a4308_0
secretstorage             3.3.1            py38h06a4308_1
setuptools                68.0.0           py38h06a4308_0
sip                       6.6.2            py38h6a678d5_0
six                       1.16.0             pyhd3eb1b0_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.4              py38h06a4308_0
sphinx                    5.0.2            py38h06a4308_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.4.3            py38h06a4308_1
spyder-kernels            2.4.4            py38h06a4308_0
sqlite                    3.41.2               h5eee18b_0
stack_data                0.2.0              pyhd3eb1b0_0
statsmodels               0.14.0           py38ha9d4c09_0
tbb                       2021.8.0             hdb19cb5_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss2                  1.2.1            py38h06a4308_0
tk                        8.5.19                        2    conda-forge
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py38h06a4308_0
tomlkit                   0.11.1           py38h06a4308_0
tornado                   6.3.2            py38h5eee18b_0
traitlets                 5.7.1            py38h06a4308_0
typing-extensions         4.7.1            py38h06a4308_0
typing_extensions         4.7.1            py38h06a4308_0
ujson                     5.4.0            py38h6a678d5_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.16          py38h06a4308_0
watchdog                  2.1.6            py38h06a4308_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    py38_1
whatthepatch              1.0.2            py38h06a4308_0
wheel                     0.38.4           py38h06a4308_0
wrapt                     1.14.1           py38h5eee18b_0
wurlitzer                 3.0.2            py38h06a4308_0
xz                        5.4.2                h5eee18b_0
yaml                      0.2.5                h7b6447c_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.4                h2531618_0
zipp                      3.11.0           py38h06a4308_0
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hc292b87_0

SYSTEM: CentOS7.9

**Comment by dmnfarrell** [comment]
this looks like a matplotlib installation problem. try `pip install matplotlib`, it will probably fail.

**Comment by hazardary** [comment]
Thanks. That' the problem.

**Comment by hazardary** [comment]
Thank. That's the problem
