### ISSUE TITLE
Showing a datetime index in Dataexplore?

### ISSUE THREAD

**Issue by AllanHOlesenBW** [dmnfarrell/pandastable#250]
I have a dataframe with a datetimeindex as row index. I have tried to use pandastable to view this dataframe. 

I see the column index names without any problems, but the row index is not visible. I just get numbered rows, starting at 1:

![01-03-2024 17-34-55](https://github.com/dmnfarrell/pandastable/assets/104567177/0618cea4-f976-4b0c-b1aa-cae4a77bb310)

The row index is still there somewhere in the background, because if I right click the index and select "Reset index", the index gets turned into a normal column, and I can now see the datetime values:

![01-03-2024 17-35-28](https://github.com/dmnfarrell/pandastable/assets/104567177/f4994800-e0ce-4158-86a3-99e91de921fe)

I use this class to show the dataframe.

```
# Example from https://pandastable.readthedocs.io/en/latest/examples.html
# Slightly modified to take a dataframe as init argument
class TestApp(Frame):
        """Basic test frame for the table"""
        def __init__(self, df:pd.DataFrame, parent=None):
            self.parent = parent
            Frame.__init__(self)
            self.main = self.master
            self.main.geometry('1200x800+400+400')
            self.main.title('Table app')
            f = Frame(self.main)
            f.pack(fill=BOTH,expand=1)
            #df = TableModel.getSampleData()
            self.table = pt = Table(f, dataframe=df,
                        showtoolbar=True, showstatusbar=True)
            pt.show()
            #set some options
            options = {'colheadercolor':'green','floatprecision': 5}
            config.apply_options(options, pt)
            pt.show()
            return
```

And I call the class like this, where df is a dataframe generated elsewhere in my code.

    app = TestApp(df=df)
    #launch the app
    app.mainloop()

**Comment by dmnfarrell** [comment]
I cant replicate this. If you open the dataexplore app there is sample data that has a date column and that seems to work. You could print out the dtypes of your table.

**Comment by AllanHOlesenBW** [comment]
I am not talking about a datetime column. I am talking about a datetime index.

Anyway, it seems that I focused too much on the datetime part in my original search in the documentation. This happens across all types of row index. And I have now figured out that the solution is table.showIndex() (as per Issue #152).

But now I am curious. What is the reason for hiding the row index as default? I can't imagine many use cases where I would not want to see the row labels.

**Comment by dmnfarrell** [comment]
Yes I know what you meant. Anyway as you found out its just the showindex problem I can close this. You have a point about the index being invisible by default. It can be confusing. Maybe it needs to be more obvious in the documentation. I'm not sure changing the default behaviour is a good idea now though as quite a few people use this library.
