### ISSUE TITLE
Feature wishes: implement dview-like data inspection features

### ISSUE THREAD

**Issue by dacoex** [dmnfarrell/pandastable#27]
Dear developer(s),

for environmental, meteo and engineering data, the following software has nice plotting features:
https://beopt.nrel.gov/downloadDView

Quick:
- re-sampling from hourly daily, monthly
- Heat Map
- (daily / annual) Profile
- Statistics
- PDF/CDF
- Duration curve
- Scatter

Since Dview has no python power, it would be great t have the same functionality available in datatable.

OK, maybe I need to see if I could learn how to write a plugin....

**Comment by dmnfarrell** [comment]
Yes if you want quite specific functionality a plugin might be best. Though some of the time series stuff would be good to add as core functions. I just haven't gotten round to it. If you want to develop your own plugin I could start you off or assist.
