### ISSUE TITLE
FAQ: run out of Ipython in Spyder?

### ISSUE THREAD

**Issue by dacoex** [dmnfarrell/pandastable#28]
Is it possible to launch datatable out of a ipython console in Spyder IDE and then get access to all my dataframes / series?

**Comment by dmnfarrell** [comment]
Yes you can launch the application dataexplore from within the interpreter:
https://github.com/dmnfarrell/pandastable/wiki/Use-DataExplore-from-within-Python

Note that I have just changed some of the method names to make it clearer to use, so this will only work with the latest commit (i.e. not from a pip installation)

I haven't tried it from Spyder IDE but it works from a regular ipython console.
