### ISSUE TITLE
Improve compatibility with Anaconda and Python 2.7

### ISSUE THREAD

**Issue by tingtron** [dmnfarrell/pandastable#29]
With latest Anaconda and its private Python 2.7 (as a choice -- there's also a Python 3 version, but the user prefers 2.7), some imports of `Tkinter` do not work. In particular, when spelled with lower case `tkinter` or for some submodules, e.g. `tkFont` as `tkinter.font`.

With simple modification of imports following the try / except pattern, it is possible to address the issue. (See below.)

The following is reported by `conda list`:
```
anaconda                  2.4.1
python                    2.7.11
tk                        8.5.18
```

### core.py
```
try:
    ...
    import tkinter.font
except:
    ...
    import tkFont as font
```

### dialogs.py
```
try:
    import tkinter
    from tkinter import *
    ...
    from tkinter.scrolledtext import ScrolledText
except:
    import Tkinter
    from Tkinter import *
    ...
    import ScrolledText
```

### headers.py
```
try:
    from tkinter import *
    ...
except:
    from Tkinter import *
    ...
```

### images.py
```
try:
    import tkinter as tk
except:
    import Tkinter as tk
```

### plugin.py
```
try:
    import tkinter
    from tkinter import *

    from tkinter.ttk import *
except:
    import Tkinter
    from Tkinter import *
    from ttk import *
```

### preferences.py
```
try:
    from tkinter import *
    from tkinter.ttk import *
except:
    from Tkinter import *
    from ttk import *
```

### stats.py
```
try:
    from tkinter import *

    from tkinter.ttk import *
except:
    from Tkinter import *
    from ttk import *
```

### util.py
```
try:
    from tkinter import *
    from tkinter.ttk import *
except:
    from Tkinter import *
    from ttk import *
```

**Comment by dmnfarrell** [comment]
I just made updates (version 0.7.1) to support python 2.7 and it works with pip. For Python 2.7 you need the future and pyttk modules installed. Give that a try? I haven't tested anaconda installs on windows or OSX though so let me know if it works.

**Comment by dmnfarrell** [comment]
btw are you installing with this package:
https://anaconda.org/dmnfarrell/pandastable

**Comment by tingtron** [comment]
Thank you for clarification and suggestions. A very nice and powerful little tool.

I installed following the github instructions (using pip), assuming that anaconda for Python 2.7 is based, by and large, Python 2.7. Regarding the anaconda repository, good to know. But I have 32-bit version of anaconda, which may be true for other users. (Not the best choice for large data processing, but may still be the case.)

I was thinking along the lines of bringing the environment to support the new `tkinter`, but then I saw in the code the try / except pattern, which was almost working for both 2.7 and 3. So it was possible to fix it in a fairly straightforward way: anything related to `tkinter` outside of try/except move inside.

The only question I had: would the proposed changes not work? Or was there a reason to only partially keep the `tkinter` related imports inside try/except?

I am expecting that other users may stumble against the same issue with Python 2.7. And that's part of the reason people stick with 2.7 to avoid the complications of "future" and backward compatibility brought about with 3.

**Comment by dmnfarrell** [comment]
Your changes work fine. I am happy to make these changes to make the code consistent.
I just left some of the imports out of the try/except because with future installed it doesn't really matter. Some imports do certainly need an alternative python 2 import such as simpledialog so I really used the try/except pattern for that and ttk.

But I am pretty sure future is required to run it on python 2.7 anyway. future also provides support for other things apart from tkinter imports.

Isn't it just a matter of installing future with conda or pip? 
I understand that some people want to stick to python 2.7 so want to get it working properly for those people. I just really need to make future a dependency in the setup file so it will be installed with pip (or conda) automatically for 2.7.

**Comment by tingtron** [comment]
Actually, you are right: `future` package is required (*), and with it installed, the support for `tkinter` works fine. What happened in my case, is that after addressing all `Tkinter` (retrofitting try/except) I got the issue with:
  (*) other than for `tkinter`, the `future` package is required for `builtins` et al

And I didn't re-test uninstalling and reinstalling pandastable again. Now that I did, I see that it does not need the retrofitting above once `future` is installed.

On a side note, for Windows and Anaconda, is `pyttk` really required? I tried with and without it installed and saw no difference. (I suppose it should help displaying some UI controls more "native" looking.) But it might be the case only for Linux.

Another note: I couldn't easily find how to run pandastable from command-line to diagnose issues. The `dataexplore` executable hides error messages. So I used the following:
```
>python -m pandastable.app
```

![pandastable_win10](https://cloud.githubusercontent.com/assets/2383820/12864499/7ef41e6a-cc5a-11e5-8937-0904348b855f.png)

**Comment by dmnfarrell** [comment]
Thanks for your input. I have changed a few of the imports anyway to clean them up. `future` is now a dependency for pip. You're right `pyttk` is not needed. For some reason I thought ttk wasn't in the standard library in 2.7.
For the error messages I will have to add some sort of logging possibly. But I will add the command you used to the wiki so people are aware they use that. Thanks.
BTW if you have a mac or know anyone who can test it on OSX that would be useful.
