### ISSUE TITLE
dataexplore crashes

### ISSUE THREAD

**Issue by rogermosher** [dmnfarrell/pandastable#33]
when I try to run dataexplore it crashes the python interpreter.  I am using python 3.5.1 and ironpython, tho it failed with the regular python interpreter as well.

when I try to run main.py directly I get the following error

C:\pandasTable>ipython main.py
C:\Anaconda3\lib\site-packages\matplotlib\__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect because the backend has already been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot, or matplotlib.backends is imported for the first time.

 warnings.warn(_use_error_msg)
['example', 'ipythonview', 'rename', 'seabornplots']
[]

It does bring up an empty "frame" ; that is, a window which has an outer frame but is transparent otherwise.

**Comment by dmnfarrell** [comment]
Perhaps because you are running using `ipython main.py`? That actually works for me but it's not meant to be called with ipython and will likely cause problems. Just try using `python main.py`.

**Comment by rogermosher** [comment]
It doesn't seem to make a difference, but I downloaded it from the DataExplore website and it works just fine thanks
