### ISSUE TITLE
Immediate crash on windows/anaconda

### ISSUE THREAD

**Issue by gvoysey** [dmnfarrell/pandastable#37]
Using Python 3.5.1 (anaconda 2.5.0) on win7 x86_64. 
`pip install pandastable` executes cleanly.  

from the anaconda command prompt:

`[Anaconda3] C:\Projects> dataexplore` 
results in: 
![capture](https://cloud.githubusercontent.com/assets/3641839/13955222/3e178b6e-f01a-11e5-9690-c109b8c1b961.PNG)

and no command-line output for debug is available.

**Comment by gvoysey** [comment]
I grabbed some debug by digging through the stack trace a little: 

>Unhandled exception at 0x000000000FFF65A9 (tcl86t.dll) in pythonw.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by dmnfarrell** [comment]
I will have to properly test this on anaconda in windows. You can also install this package with conda rather than pip. It might be worth trying. 
conda install -c https://conda.anaconda.org/dmnfarrell pandastable

**Comment by gvoysey** [comment]
no joy. 

I get some more command line output: 
```
C:\Users\gvoysey\Anaconda3\lib\site-packages\matplotlib\__init__.py:1350:
UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
['example', 'ipythonview', 'rename', 'seabornplots']
[]
```

**Comment by dmnfarrell** [comment]
This is a matplotlib issue since it works when the application is launched without the plot frame. The solution is to remove the conda version of matplotlib and install it with pip instead. It seems the conda package is broken with TkAgg. see https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/xssOnleIPFw

**Comment by gvoysey** [comment]
Okay, i'll try and update this thread.

**Comment by gvoysey** [comment]
@dmnfarrell you're spot-on; this is a matplotlib-on-anaconda issue.  Thanks for the prompt detective work!
