### ISSUE TITLE
CI: ImportError: Building pandas requires cython

### ISSUE THREAD

**Issue by Ismael-VC** [dmnfarrell/pandastable#46]
Cython is needed in order for the Continuous Integration system to work.
- https://travis-ci.org/dmnfarrell/pandastable/jobs/170915671#L1674

``` python

    ImportError: Building pandas requires cython

    ----------------------------------------
    Command "/home/travis/virtualenv/python3.4.2/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-5xny5235/pandas/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wxzhxc9t-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python3.4.2/include/site/python3.4" failed with error code 1 in /tmp/pip-build-5xny5235/pandas

The command "pip install numpy matplotlib numexpr xlrd pandas" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by dmnfarrell** [comment]
Yes I noticed this as it's triggered every time I push a commit. I just haven't gotten round to fixing it. Cheers.

**Comment by Ismael-VC** [comment]
> I just haven't gotten round to fixing it.

Then could you please leave this issue open until it's fixed?

I'll try to fix it this this weekend. I use both Travis CI and AppVeyor, but I haven't tested GUIs before. We just need to update the build scripts. 

But then again there are no Unit Tests, so I don't know if you don't want/need to fix this. May I suggest disabling the CI builds for now. If there is anything I can do, please let me know.

**Comment by dmnfarrell** [comment]
There may be a faster way to build matplotlib/numpy/pandas on travis such as using wheels? If you are familiar with this by all means I will accept your fix. 
Also there are unit tests, though they are not very comprehensive as Tkinter unit tests are hard to implement to my knowledge. If you look at the .travis.yml file you see the tests are used.

**Comment by Ismael-VC** [comment]
Thanks for re opening. I have time to check this out this week. I'll also look into tkinter unit tests to make it worthwhile.
