### ISSUE TITLE
Memory Leak in Table class!

### ISSUE THREAD

**Issue by 816-8055** [dmnfarrell/pandastable#47]
Each redraw of a Table instance consumes an average of 21kB RAM on an "empty" table.
With a filled Table it's even more.

To prove the problem, I wrote a small application which refreshes 100 times a second, calculates the average additional consumed memory and shows also the total consumed memory:

```python
import psutil
import tkinter as tk
import pandastable

FREQ = 100  # redraws per second


def update_title():
    global N, S
    mem = me.memory_full_info().uss
    table.redraw()
    diff = me.memory_full_info().uss - mem
    S += diff
    N += 1
    root.title('total: {:.2f}MB - added per redraw: {:.2f}kB'
               .format(mem / 1000**2, (S/N)/1000))
    root.after(1000//FREQ, update_title)

if __name__ == '__main__':
    N = 0
    S = 0
    me = psutil.Process()
    root = tk.Tk()
    frame = tk.Frame(root)
    table = pandastable.Table(frame)
    table.show()
    frame.pack(fill='both', expand=True)
    root.after(100, update_title)
    smu = me.memory_full_info().uss
    root.mainloop()
    print('{:.2f}MB'.format((me.memory_full_info().uss-smu)/1000**2))
```
![pandastable_memleak](https://cloud.githubusercontent.com/assets/5756974/20525465/e996c94e-b0bf-11e6-9eaf-08c4b3e2091b.png)

**Comment by 816-8055** [comment]
Commenting out line 311 in file core.py reduces the memory usage by 3kB per redraw.
Creating a new canvas on each redraw doesn't look like a good idea to me!

```python
    def redrawVisible(self, event=None, callback=None):
        """Redraw the visible portion of the canvas"""

        model = self.model
        #self.scratch = Canvas()
        self.rows = len(self.model.df.index)
        self.cols = len(self.model.df.columns)
```

**Comment by dmnfarrell** [comment]
Great. Not sure why this line was ever needed to be honest. Thanks for taking the time to check that. I will make a minor update soon and add that change in.
