### ISSUE TITLE
Enhancement for Table.copy

### ISSUE THREAD

**Issue by 816-8055** [dmnfarrell/pandastable#49]
Currently if only one cell is selected in the table and the selection is copied to the clipboard, the whole column including index and column label is actually written to the clipboard.
In my opinion it would be more intuitive if only the selected value is copied.
Additionally when one column or a part of a column is selected, only the selected values should be copied.
When whole rows or more than one column is selected, the data should be copied as it is now.

What do you think?

**Comment by 816-8055** [comment]
For example like [this](https://github.com/816-8055/pandastable/commit/e4908db459f83e058559c770071fd5f864fe75c0)

**Comment by dmnfarrell** [comment]
Yes that looks good. If you can make a pull request I can merge as is. Thanks. There are a good few features like this that need improvement.. FYI the travis builds are breaking at the moment but they don't test the gui interaction anyway.
