### ISSUE TITLE
IPython console errors with attribute error

### ISSUE THREAD

**Issue by kmatt** [dmnfarrell/pandastable#53]
Just installed 0.7.2 with pip install into Anaconda Python 3.5.2, and upon a clean launch and selecting Plugins -> IPython console presented with an error dialog:

    'InteractiveShellEmbed' object has no attribute 'prompt_manager'

The only messages I see in the console are:

    2017-01-24 14:09:12.315 python[82437:47518047] setCanCycle: is deprecated.  Please use setCollectionBehavior instead

**Comment by dmnfarrell** [comment]
the ipython api has changed since i wrote this. will take a look.

**Comment by kmatt** [comment]
The version I am testing with is IPython 5.1.0

**Comment by cgclark** [comment]
I am having the same issue. Would this allow the python code that is being used to generate the plot to be viewed?

**Comment by dmnfarrell** [comment]
Yes you could plot in the app from the console if that's what you mean. But this was broken with newer versions of ipython and it probably requires a re-write. I haven't had time to do that yet.

**Comment by cgclark** [comment]
Just to clarify, I made an assumption that python code (that we do not see) is generated by dataexplore across various already implemented functions, e.g. in generating a certain type of plot. I was curious whether it might be possible to a) view said python code via a console, not b) call capabilities (which I suppose could be done inside a jupyterlab notebook).

**Comment by dmnfarrell** [comment]
Yes someone was asking about this before. The plots are created using matploltlib calls obviously but wrapped inside the plotting module. There is no way I know of to reproduce these commands in the console and in a way that would be meaningful.
