### ISSUE TITLE
core.py importerror

### ISSUE THREAD

**Issue by ljstrnadiii** [dmnfarrell/pandastable#56]
I have been having issues with loading tkinter. I use 2.7.8 and apparently tkinter is for 3. In the core.py file of in pandastable we have 

"from tkinter import font"

outside the try statement for tkinter. I have to move the line into the try in order to get thing working again. 

Figured I would tell you to either get an explanation or fix so i can pip again

Cheers

**Comment by dmnfarrell** [comment]
It works on python >=2.7 and >=3.5. For python2 you need to install the future package:
pip install future

I guess this needs to be added by default as a requirement.

**Comment by ljstrnadiii** [comment]
Requirement already satisfied.

Still I get an import error

 "Can not import name _splitdict"

Which I also get when I try to import tkinter in the interpreter

**Comment by dmnfarrell** [comment]
Maybe update your python 2.7 version?
