### ISSUE TITLE
Bug in Table.copy for colums with length > 50

### ISSUE THREAD

**Issue by 816-8055** [dmnfarrell/pandastable#58]
In fix for #49 is a bug which causes that strings longer than `pandas.options.display.max_colwidth` (defaults to 50) are truncated when copying the value of a single cell to clipboard.

Example data:

    pandas.DataFrame(['a very long string inside a pandas.DataFrame instance'])
`'a very long string inside a pandas.DataFrame i...'` is copied to the clipboard.

**Comment by dmnfarrell** [comment]
Is your fix ok and can I merge it.
