### ISSUE TITLE
Can't get DataExplore window after matplotlib.use("TkAgg") + plt.figure() 

### ISSUE THREAD

**Issue by aivarannamaa** [dmnfarrell/pandastable#61]
Following code returns but fails to bring up DataExplore window:

```python
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from pandastable.app import DataExplore

fig = plt.figure()
app = DataExplore()
```

If I comment out either `matplotlib.use('TkAgg')` or `fig = plt.figure()`, then DataExplore window appears.

Platform: Anaconda 4.4.0, 64-bit Windows 10.

**Comment by aivarannamaa** [comment]
Looks like it's not an issue when `plt.show` is also used:

```python
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from pandastable.app import DataExplore

fig = plt.figure()
plt.show()
app = DataExplore()
```

**Comment by dmnfarrell** [comment]
Is this from a script or in the interpreter?
Using IPython you can do:

%gui tk #ipython magic
from pandastable.app import DataExplore
app = DataExplore()

**Comment by aivarannamaa** [comment]
I tested it both in IPython (using %gui tk) and in my own IDE (http://thonny.org), which also supports Tk eventloop. 

Anyway, it looks like the case I mentioned is not very likely in normal use, so feel free to close this issue if you don't consider it important.

PS. Here's a screenshot how the users of my IDE can now invoke dataexplore:

![image](https://user-images.githubusercontent.com/1802/27299342-c55798b4-5534-11e7-8c67-3e720804f949.png)

**Comment by dmnfarrell** [comment]
Using from ipython is documented here https://github.com/dmnfarrell/pandastable/wiki/Use-DataExplore-from-within-Python
I can add a mention about using your app on that page if you want.

**Comment by aivarannamaa** [comment]
> I can add a mention about using your app on that page if you want.

That would be really nice, but I haven't released this functionality yet. I'll let you know when I've completed the release and written the documentation.

**Comment by dmnfarrell** [comment]
No problem.
