### ISSUE TITLE
table.getRecName(rowIndex) not implemented

### ISSUE THREAD

**Issue by joschuck** [dmnfarrell/pandastable#63]
Hi,

while using `getRecordAtRow` from `TableModel` I had an atrribute error and it seems like `getRecName` is not implemented.

Code to create table:
    self.table = Table(self.table_tab, dataframe=pd.DataFrame(np.random.randn(5, 5), columns=[' A ', ' B ', 'C', 'D', 'E']))

  File "/Users/johannes/NPYViewer_Virtual_Environment/lib/python2.7/site-packages/pandastable/data.py", line 134, in getRecordAtRow
    name = self.getRecName(rowIndex)
AttributeError: 'TableModel' object has no attribute 'getRecName'

pandastable/pandastable/core.py lines 141, 142

        name = self.getRecName(rowIndex)
        record = self.df.ix[name]

A possible fix would be the following line of code (if not, why?)

        record = self.df.iloc[rowIndex]

I have no previous experience with pandas.

**Comment by dmnfarrell** [comment]
Yes getRecordAtRow is a legacy method I obviously left in but is never used. So the error normally wouldn't be seen unless you call the method explicitly. If you have a specific need for that function I can certainly fix it otherwise I'd recommend you just access the underlying dataframe if you want access to a row? 

```
df = table.model.df #the dataframe
df.index[0] #index of first row 
df.iloc[df.index[0]] #first row 
```

**Comment by dmnfarrell** [comment]
Sorry that should be
```
df.iloc[0] #first row 
or
df.ix[df.index[0]] #first row 
```

**Comment by joschuck** [comment]
No I have no specific need for that function, i just used the underlying dataframe as well.
I also noticed `columnNames` in `getColumnData(colIdx)` is outdated as well. Nevertheless I think it's more convenient to have those functions in the API.

**Comment by dmnfarrell** [comment]
Yes I will just fix them. They may be useful for someone not used to pandas. These are here because this was developed from a previous version that used dicts as the back end and a lot more helper functionality was needed in the model class. Cheers.
