### ISSUE TITLE
Numbers with scientific notation

### ISSUE THREAD

**Issue by mandlerd** [dmnfarrell/pandastable#64]
Columns with number numbers in scientific notation (e.g. 1.34646393e-8 ) are shown as 0.0. When you double click on a cell it is shown right!

Can this be fixed?

**Comment by dmnfarrell** [comment]
Ok it's rounding off to several decimal places and small numbers are rounded to zero. I can fix that.

**Comment by mandlerd** [comment]
Thanks, would be great!

**Comment by dmnfarrell** [comment]
This should be fixed. Small numbers will now be shown as floating point if they are lower than about 1e-4.

**Comment by mandlerd** [comment]
Thanks! Works great! Would it be also possible to implement a selection of how many digits are shown in the csv import form? e.g. 3 -> .3e!

**Comment by dmnfarrell** [comment]
You mean how many digits to round off to when importing a csv? If so I think it would be better to add

**Comment by mandlerd** [comment]
My usecase is that I get .csv files with numbers in scientific notation. For example 2.345689e-6. So when I then want to display them with pandastable, I want to be able to limit the number of digits after the comma. So that the number of if displayed as 2.346e-6 when I set the number of digits to 3!

So yes, how many digits to round off when importing a csv.

**Comment by dmnfarrell** [comment]
I think what you want is an option to display a certain precision? Rounding off the numbers is different and could result in making small numbers zero. I think this would have to be a separate option somewhere as it's a display setting and not directly related to csv import.

**Comment by mandlerd** [comment]
Yes you are right!

**Comment by dmnfarrell** [comment]
There is now an option in the table preferences (edit menu or right click on table) to change the float precision. Your column has to be of type float for it to work, i.e. all numbers. A value of 0 means the raw values are used.
