### ISSUE TITLE
Reload content of csv file

### ISSUE THREAD

**Issue by mandlerd** [dmnfarrell/pandastable#66]
Would it be possible to add a feature to reload data from a csv file? In my use-case a get results in csv format from a simulator. After a new simulation run, a fast refresh of the table would be very convenient.

**Comment by dmnfarrell** [comment]
I think in your case a plug-in would be best, then you could set it to update the plot etc when the csv file changes in real time and any other custom things you need. Can you program with Python?

**Comment by mandlerd** [comment]
I had already a look on the plugin ability and was thinking about it, because I need also additional functions. Maybe we can get in touch over another media, than the Issue reporting.

**Comment by dmnfarrell** [comment]
Sure, if you go to the journal article page my contact mail is there.

**Comment by dmnfarrell** [comment]
Will I close this issue or did you want to address it further?

**Comment by mandlerd** [comment]
I will contact you via mail. Thanks.
