### ISSUE TITLE
Pivot function

### ISSUE THREAD

**Issue by ahamza83** [dmnfarrell/pandastable#68]
hi, the pivot function is missing the 'aggfunc' argument, so it's set to 'mean' by default, I needed it to be sum so I added it to the function at the core.py file.
I know of course that the dialogue file will have to be edited accordingly adding a field for the list of functions, so I thought you might want to add it, just to let you know, but thanks anyways for this great module.

**Comment by dmnfarrell** [comment]
Thanks, this is now fixed.
