### ISSUE TITLE
Strange error at plotting time

### ISSUE THREAD

**Issue by solalatus** [dmnfarrell/pandastable#69]
I am trying to make a mini Tk app that includes Pandastable.
So far loading the data is ok, can resize canvas and stuff, but when I try to plot a field (which I have modifeied the type to be Int via the GUI with no problems), I get this:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/lev/anaconda3/envs/pandastable/lib/python3.5/tkinter/__init__.py", line 1559, in __call__
    return self.func(*args)
  File "/home/lev/anaconda3/envs/pandastable/lib/python3.5/site-packages/pandastable/core.py", line 2362, in plotSelected
    self.pf = PlotViewer(table=self)
  File "/home/lev/anaconda3/envs/pandastable/lib/python3.5/site-packages/pandastable/plotting.py", line 75, in __init__
    self.setupGUI()
  File "/home/lev/anaconda3/envs/pandastable/lib/python3.5/site-packages/pandastable/plotting.py", line 157, in setupGUI
    self.nb.add(w2, text='Styles', sticky='news')
  File "/home/lev/anaconda3/envs/pandastable/lib/python3.5/tkinter/ttk.py", line 840, in add
    self.tk.call(self._w, "add", child, *(_format_optdict(kw)))
_tkinter.TclError: can't add .140293231192664 as slave of .140293312652400.140293231660728.140293231691872
`
As visible, I am on Anaconda, Python 3.5, clean virtualenv, only Pandastable and Pandas installed.

My code is pretty basic (an may well be totally messed up! :-P
`
from tkinter import *
from pandastable import Table, Frame

class MainWindow:
	
	def __init__(self, master):
		self.master = master
		master.title("A simple GUI")
		fr = Frame(master)

		fr.pack(fill=BOTH, expand=YES)
		pt = Table(fr)
		pt.show()
		pt.importCSV('/home/lev/aipartners/mailscraping/emails.csv')
		pt.redraw()
root = Tk()
w, h = root.winfo_screenwidth(), root.winfo_screenheight()
root.resizable(width=True, height=True)
win = MainWindow(root)
root.mainloop()
`

Any clues on what might be going on?

Thanks!

**Comment by dmnfarrell** [comment]
Your code is ok. This was a bug in creating the plot widgets. It should be fixed now.

**Comment by solalatus** [comment]
I've pulled, and now plotting comes up!
Really nice.

Now something other and non intuitive happens:

![screenshot 2017-08-12 14-16-19](https://user-images.githubusercontent.com/11365719/29240620-08fd9506-7f69-11e7-996c-c55568ab8374.png)

I might be totaly lame in Python plotting, but my expectation would be, that if "Use index" is checked in, index goes linearly from 1-40 and "data" from 121-160, the resulting plot should be a straigth line.
Seems to me, that index ordering is not respected somehow, since index 5 is at the end.

As said, this might be a default (but sad) behavior from matplotlib, but I would be interestd in your take on this! 

Thanks a lot for the blitz-fast help! Really appreciated!

**Comment by dmnfarrell** [comment]
It's nothing to do with matplotlib. The index is any arbitrary column and by default its not visible. What you see is the row number by default, these are always ordered from 1 up but the index can be in any order. So if you toggle the index (right click on row header) you will see that it is not sorted exactly in the same order as the rows for some reason. Therefore you get that plot. What you can do is to reset the index using ```pt.resetIndex()```

**Comment by solalatus** [comment]
Works like charm! Thx!
