### ISSUE TITLE
Feature request: A conventient way to change cell colour

### ISSUE THREAD

**Issue by eedahl** [dmnfarrell/pandastable#70]
I have a DF with around 6500 entries, and would like to highlight cells in given rows which satisfy a certain criterion. Specifically, I want to run through each cell of a given column with a regex to detect numbers; then, if a number is detected, set the cell colour to, say, green if the value is over greater than -10. I'm currently searching the code base for a nice way to do this, but I haven't had success much success yet.

Regards,
Eivind

**Comment by dmnfarrell** [comment]
Yes you can't currently color cells. It's certainly possible to implement though. It could be combined with the filtering tool to highlight rows corresponding to your search rather than limit the table to the filtered results. That would be the quickest thing to implement if it's sufficient.

**Comment by eedahl** [comment]
That would be useful. I'm not too familiar with the filtering tool, so I'm not quite sure whether it does what I want. If it's any help, right now I apply a filtering function to the dataframe to get a mask. The function uses data from some entry boxes, and I process both the entered text and the cell text with some regular expressions and compare. This gives me a new dataframe. I update the dataframe and redraw. If I could use this same or a similarly acquired mask as data to change cell colours in prescribed columns, that would be ideal for my purpose.
```
mask = df[[CHAR, CMD, HL, SUF, BF, HF, CHF, NOTES]].apply(filter_row, axis=1)
tf = df[mask]
...
table.model = TableModel(tf)
...
table.redraw()
```
The function `filter_row` compares cell data with some input data via some regular expressions.

It's another issue, but if I could similarly use masks to hide rows (and columns) from view without swapping the underlying dataframe that would be similarly useful, so I could manipulate and change the table view and have changes applied directly to the master dataframe.

**Comment by dmnfarrell** [comment]
You can now do this for highlighting rows you have filtered:

```
tf = df[mask]
idx = tf.index
self.multiplerowlist = self.getRowsFromIndex(idx)
self.redraw()
```

The highlight color can be changed in preferences. It highlights the whole row though. See if it works.
For using masks to hide rows/cols this should be quite easy, I will look at it.

**Comment by eedahl** [comment]
Oh, that's a nice start. I'll have a look at it later tonight.

**Comment by dmnfarrell** [comment]
You can now change column colors via the columncolors dict. https://github.com/dmnfarrell/pandastable/wiki/Table-Coloring

**Comment by eedahl** [comment]
Nice! Will you be able to change particular cells (according to a mask) within a column too? That would satisfy this FR completely.

**Comment by dmnfarrell** [comment]
If the column is colored and you set the selected rows then they will be highlighted a darker color.
So you can just do this:

```
table.multiplerowlist  = table.getRowsFromMask(mask)
```

![selections](https://user-images.githubusercontent.com/7859189/29692797-db6dee72-8929-11e7-9737-030d0bd26c63.png)

**Comment by eedahl** [comment]
It's something, but ideally I'd be able to set different colours for different masks. I filter the data with several different criteria, and produce a mask for each, meaning some cells in a column which satisfy no criteria will remain the default colour, while others blue, red or yellow according to the mask.

```
mask_1 = df[[some_col_1, ..., some_col_n]].apply(filter_row_1, axis=1)
mask_2 = df[[some_col_1, ..., some_col_n]].apply(filter_row_2, axis=1)
table.setColourByMask('column_name', mask_2, colour)
table.redraw()
```

**Comment by dmnfarrell** [comment]
It's trivial to set cell colors but the table is optimized to only draw what's visible. So setting individual colors has to be integrated into the redraw method. I'll have another look when I get time.

**Comment by dmnfarrell** [comment]
You can now do `table.setColorByMask(column, mask, color)` and it should give the behaviour you need. 

This works by using a mirror dataframe called `table.rowcolors` that adds a column when you call the above method. So to clear this use `table.clearFormatting()` or set  rowcolors to an empty dataframe. Changes to the table will likely lose the formatting though you can alter the index and it should still work. So I'd recommend to regenerate your masks and re-do the colors if u to alter the table. There are probably a few bits that need to be added to clean it up.

![cellcolors](https://user-images.githubusercontent.com/7859189/29788137-743e4758-8c29-11e7-927e-cb1184fa2a20.png)
