### ISSUE TITLE
Problem installing pandastable on my Mac OS X 10.12.6

### ISSUE THREAD

**Issue by davewd** [dmnfarrell/pandastable#71]
Hey - having real issues installing this package... seems to be based on relative file path, I've tried a good google, but nothing obvious surfaces : 

D:~ d$ pip install pandastable
Collecting pandastable
  Using cached pandastable-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tr/ljc_bj7x2hj7d2q2vcnwbp0r0000gn/T/pip-build-2l0_3s6l/pandastable/setup.py", line 5, in <module>
        with open('description.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'description.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tr/ljc_bj7x2hj7d2q2vcnwbp0r0000gn/T/pip-build-2l0_3s6l/pandastable/
D:~ d$

**Comment by dmnfarrell** [comment]
Yes this file was missing in the source distribution and broke pip installs in the current release. I'll release an update shortly and it should work. Thanks for letting me know.

**Comment by davewd** [comment]
Is there a way I can generate a new release version ? (Sorry your viewer is exactly what I've been looking for for the last month and I'm keen to get stuck in !!)

**Comment by dmnfarrell** [comment]
You can just get the current source https://github.com/dmnfarrell/pandastable/archive/master.zip and install from that. But I will make a new release today anyway since it's broken.

**Comment by dmnfarrell** [comment]
I've made a new release that should fix the pip install problem.
