### ISSUE TITLE
Deleting a row in the table with duplicate time stamps removes all rows with that timestamp

### ISSUE THREAD

**Issue by MattAcker1987** [dmnfarrell/pandastable#72]
when I have the data in the table and right click to remove a row, all the rows with duplicate indexes end up getting deleted. I am trying to fix the bug myself but can't seem to track down the source of the bug. Anybody know where I can look? I am using DataExplore Application when this happens.

**Comment by dmnfarrell** [comment]
Yes this is a pretty major bug that I had overlooked somehow. I'll take a look.

**Comment by dmnfarrell** [comment]
This should now be fixed. Behaviour now is to only delete rows you have selected, regardless of duplicate indexes.
