### ISSUE TITLE
Autoscroll on down key

### ISSUE THREAD

**Issue by parvathycec** [dmnfarrell/pandastable#74]
Hi, 
When I press down key, focus goes to next row. However, autoscroll does not work and we don't see the cell which has current focus. It would be good to have an auto scroll for down key for better user experience.
Thanks

**Comment by dmnfarrell** [comment]
Yes that needs fixing.  Are you using windows or Linux?

**Comment by parvathycec** [comment]
Am using Windows now and have not tested in Linux.
Can I get it working from my side somehow? Do you think a binding down from my side of code will help me solve this issue?

**Comment by dmnfarrell** [comment]
If you know python and can provide the exact fix I would merge a pull request, otherwise leave it to me.

**Comment by parvathycec** [comment]
okay

**Comment by dmnfarrell** [comment]
This should be fixed for up/down arrow keys. You have to be using the git version to test though.

**Comment by parvathycec** [comment]
Okay I will test it. Thanks. Will right and left arrows work too?

**Comment by dmnfarrell** [comment]
Yes you can test right/left as well.

**Comment by parvathycec** [comment]
It works. Thanks
