### ISSUE TITLE
Progress bar not working

### ISSUE THREAD

**Issue by parvathycec** [dmnfarrell/pandastable#76]
Hi,
Will show_progressbar work? 

Thanks,
Parvathy

**Comment by dmnfarrell** [comment]
The function is there but the feature isn't implemented for loading data as it wasn't a priority. Do you need this?

**Comment by parvathycec** [comment]
It will be good to have this as the data I load is huge and it takes some time.

**Comment by dmnfarrell** [comment]
Ok I'll take a look. How big is huge and how long does it take?

**Comment by parvathycec** [comment]
Around 175500 records take around 6 seconds.

**Comment by dmnfarrell** [comment]
Loading data is much faster now so you normally shouldn't need the progress bar.
