### ISSUE TITLE
`Save the figure` does not handle correctly the file format

### ISSUE THREAD

**Issue by cardosan** [dmnfarrell/pandastable#77]
When you try to save the plot in a file format different from the default (.png) the file extension is not changed accordingly in the gui window (see below).

P.s: congrats, you have built a tremendously useful package!!!

![dataexplore](https://user-images.githubusercontent.com/11156305/36371004-195bb502-1561-11e8-8f24-672626f8a55b.png)

**Comment by dmnfarrell** [comment]
Thanks. What system are you using this on? How did you install.

**Comment by cardosan** [comment]
linux mint 17.2, installed on a newly created conda environment using pip

**Comment by dmnfarrell** [comment]
this may be fixed now because the plot toolbar is gone and there is a separate save button. it seems to work ok for me for other file formats. you can try it if using git or wait till a new release on pip.
