### ISSUE TITLE
Sort Column

### ISSUE THREAD

**Issue by parvathycec** [dmnfarrell/pandastable#78]
Hi, 

I would like to sort a column by clicking the header of the table column. It works for ascending, but is it possible to make it sort descending, the next time I click the header? Can I use any of sortTable or sortColumnIndex to achieve this?

Thanks

**Comment by dmnfarrell** [comment]
Yes it should be easy to make it re-sort in the opposite order when you double click again. If you want to do it programmatically you can check http://pandastable.readthedocs.io/en/latest/pandastable.html#module-pandastable.core for the sort method.

**Comment by parvathycec** [comment]
I got it that I can use sortTable, but it would be good if it can happen on the double click of header, which I don't know how to do.

**Comment by parvathycec** [comment]
Sorry, I got it now. I did an override of the sortTable and its working now. It would have been a nice feature to have. Do you want me to close this issue?

**Comment by dmnfarrell** [comment]
No I will add this.

**Comment by dmnfarrell** [comment]
Should work now.
