### ISSUE TITLE
plot on retina display

### ISSUE THREAD

**Issue by cgclark** [dmnfarrell/pandastable#79]
Hi, I have a high resolution (retina) display on a mac. The plot is fuzzy. In a Jupyter notebook with inline matplotlib  (e.g. %matplotlib inline), this is resolved by including:
%config InlineBackend.figure_format = 'retina'

Can something like this be implemented here?

**Comment by dmnfarrell** [comment]
This seems to be an issue with the matplotlib tkagg backend. So the jupyter command won't solve it I think.
This bug is discussed here: https://github.com/matplotlib/matplotlib/issues/10388. This seems to be a recent bug so it might get fixed. I will keep an eye on the issue.
