### ISSUE TITLE
App not launching on Python 3.6.5 Mac High Sierra

### ISSUE THREAD

**Issue by PyDataBlog** [dmnfarrell/pandastable#84]
I pip installed the app in a conda env and I get the following error when I try to run the app: 

> 2018-04-26 10:55:22.460 python[8977:688745] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f90e5f71d90
> 2018-04-26 10:55:22.462 python[8977:688745] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7f90e5f71d90'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff4289632b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x00007fff69f0cc76 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff4292ee04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 	3   CoreFoundation                      0x00007fff4280c870 ___forwarding___ + 1456
> 	4   CoreFoundation                      0x00007fff4280c238 _CF_forwarding_prep_0 + 120
> 	5   libtk8.6.dylib                      0x000000010d7bd693 TkpInit + 389
> 	6   libtk8.6.dylib                      0x000000010d72e942 Initialize + 2457
> 	7   _tkinter.cpython-36m-darwin.so      0x000000010d590da4 Tcl_AppInit + 84
> 	8   _tkinter.cpython-36m-darwin.so      0x000000010d590a7b _tkinter_create + 1115
> 	9   libpython3.6m.dylib                 0x000000010c9ff96b _PyCFunction_FastCallDict + 491
> 	10  libpython3.6m.dylib                 0x000000010ca83597 call_function + 439
> 	11  libpython3.6m.dylib                 0x000000010ca7fee8 _PyEval_EvalFrameDefault + 24952
> 	12  libpython3.6m.dylib                 0x000000010ca843dc _PyEval_EvalCodeWithName + 3436
> 	13  libpython3.6m.dylib                 0x000000010ca850fb _PyFunction_FastCallDict + 891
> 	14  libpython3.6m.dylib                 0x000000010c9b39b3 _PyObject_FastCallDict + 307
> 	15  libpython3.6m.dylib                 0x000000010c9b3ad5 _PyObject_Call_Prepend + 149
> 	16  libpython3.6m.dylib                 0x000000010c9b3771 PyObject_Call + 97
> 	17  libpython3.6m.dylib                 0x000000010ca17c5d slot_tp_init + 125
> 	18  libpython3.6m.dylib                 0x000000010ca13f59 type_call + 313
> 	19  libpython3.6m.dylib                 0x000000010c9b3981 _PyObject_FastCallDict + 257
> 	20  libpython3.6m.dylib                 0x000000010ca83498 call_function + 184
> 	21  libpython3.6m.dylib                 0x000000010ca7fee8 _PyEval_EvalFrameDefault + 24952
> 	22  libpython3.6m.dylib                 0x000000010ca843dc _PyEval_EvalCodeWithName + 3436
> 	23  libpython3.6m.dylib                 0x000000010ca84d61 fast_function + 657
> 	24  libpython3.6m.dylib                 0x000000010ca83571 call_function + 401
> 	25  libpython3.6m.dylib                 0x000000010ca7fee8 _PyEval_EvalFrameDefault + 24952
> 	26  libpython3.6m.dylib                 0x000000010ca843dc _PyEval_EvalCodeWithName + 3436
> 	27  libpython3.6m.dylib                 0x000000010ca84d61 fast_function + 657
> 	28  libpython3.6m.dylib                 0x000000010ca83571 call_function + 401
> 	29  libpython3.6m.dylib                 0x000000010ca7fee8 _PyEval_EvalFrameDefault + 24952
> 	30  libpython3.6m.dylib                 0x000000010ca843dc _PyEval_EvalCodeWithName + 3436
> 	31  libpython3.6m.dylib                 0x000000010ca84d61 fast_function + 657
> 	32  libpython3.6m.dylib                 0x000000010ca83571 call_function + 401
> 	33  libpython3.6m.dylib                 0x000000010ca7fee8 _PyEval_EvalFrameDefault + 24952
> 	34  libpython3.6m.dylib                 0x000000010ca843dc _PyEval_EvalCodeWithName + 3436
> 	35  libpython3.6m.dylib                 0x000000010ca850fb _PyFunction_FastCallDict + 891
> 	36  libpython3.6m.dylib                 0x000000010c9b39b3 _PyObject_FastCallDict + 307
> 	37  libpython3.6m.dylib                 0x000000010c9b3ad5 _PyObject_Call_Prepend + 149
> 	38  libpython3.6m.dylib                 0x000000010c9b3771 PyObject_Call + 97
> 	39  libpython3.6m.dylib                 0x000000010ca17c5d slot_tp_init + 125
> 	40  libpython3.6m.dylib                 0x000000010ca13f59 type_call + 313
> 	41  libpython3.6m.dylib                 0x000000010c9b3981 _PyObject_FastCallDict + 257
> 	42  libpython3.6m.dylib                 0x000000010ca83498 call_function + 184
> 	43  libpython3.6m.dylib                 0x000000010ca7fee8 _PyEval_EvalFrameDefault + 24952
> 	44  libpython3.6m.dylib                 0x000000010ca84cb8 fast_function + 488
> 	45  libpython3.6m.dylib                 0x000000010ca83571 call_function + 401
> 	46  libpython3.6m.dylib                 0x000000010ca7fee8 _PyEval_EvalFrameDefault + 24952
> 	47  libpython3.6m.dylib                 0x000000010ca843dc _PyEval_EvalCodeWithName + 3436
> 	48  libpython3.6m.dylib                 0x000000010ca79ca4 PyEval_EvalCode + 100
> 	49  libpython3.6m.dylib                 0x000000010caaf841 PyRun_FileExFlags + 209
> 	50  libpython3.6m.dylib                 0x000000010caaf0ee PyRun_SimpleFileExFlags + 846
> 	51  libpython3.6m.dylib                 0x000000010cac8a96 Py_Main + 3526
> 	52  python                              0x000000010c99fdf8 main + 232
> 	53  libdyld.dylib                       0x00007fff6ab26015 start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> Abort trap: 6
>

**Comment by delmeyer** [comment]
I get the same error - lots of issues with installing and running on Mac High Sierra OSX with Python 3.6+

**Comment by delmeyer** [comment]
XXXXXXXXXXXX:ALL XXXXXX$ dataexplore -i --csv=S-1-RUN-1-DD-700-KR-300-ST-CL-100-
2018-05-29 09:00:14.105 python3[40060:3190110] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f8556b829f0
2018-05-29 09:00:14.135 python3[40060:3190110] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7f8556b829f0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4859c6bb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6fcb8942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff486339e4 -[NSObject(NSObject) 
                                                               doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff48514183 ___forwarding___ + 1443
	4   CoreFoundation                      0x00007fff48513b58 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000000109d5946f TkpInit + 383
	6   libtk8.6.dylib                      0x0000000109cb221e Initialize + 2622
	7   _tkinter.cpython-36m-darwin.so      0x0000000109ad8a16 _tkinter_create + 1174
	8   python3                             0x0000000108aecb78 _PyCFunction_FastCallDict + 200
	9   python3                             0x0000000108bc424f call_function + 143
	10  python3                             0x0000000108bc1f4c _PyEval_EvalFrameDefault + 47100
	11  python3                             0x0000000108bb5589 _PyEval_EvalCodeWithName + 425
	12  python3                             0x0000000108bc4e15 _PyFunction_FastCallDict + 373
	13  python3                             0x0000000108a6ae80 _PyObject_FastCallDict + 320
	14  python3                             0x0000000108a92468 method_call + 136
	15  python3                             0x0000000108a724ee PyObject_Call + 62
	16  python3                             0x0000000108b14065 slot_tp_init + 117
	17  python3                             0x0000000108b185b1 type_call + 241
	18  python3                             0x0000000108a6adf1 _PyObject_FastCallDict + 177
	19  python3                             0x0000000108bc4348 call_function + 392
	20  python3                             0x0000000108bc1f4c _PyEval_EvalFrameDefault + 47100
	21  python3                             0x0000000108bb5589 _PyEval_EvalCodeWithName + 425
	22  python3                             0x0000000108bc46aa fast_function + 362
	23  python3                             0x0000000108bc42ac call_function + 236
	24  python3                             0x0000000108bc1f4c _PyEval_EvalFrameDefault + 47100
	25  python3                             0x0000000108bb5589 _PyEval_EvalCodeWithName + 425
	26  python3                             0x0000000108bc46aa fast_function + 362
	27  python3                             0x0000000108bc42ac call_function + 236
	28  python3                             0x0000000108bc1f4c _PyEval_EvalFrameDefault + 47100
	29  python3                             0x0000000108bb5589 _PyEval_EvalCodeWithName + 425
	30  python3                             0x0000000108bc46aa fast_function + 362
	31  python3                             0x0000000108bc42ac call_function + 236
	32  python3                             0x0000000108bc1f4c _PyEval_EvalFrameDefault + 47100
	33  python3                             0x0000000108bb5589 _PyEval_EvalCodeWithName + 425
	34  python3                             0x0000000108bc4e15 _PyFunction_FastCallDict + 373
	35  python3                             0x0000000108a6ae80 _PyObject_FastCallDict + 320
	36  python3                             0x0000000108a92468 method_call + 136
	37  python3                             0x0000000108a724ee PyObject_Call + 62
	38  python3                             0x0000000108b14065 slot_tp_init + 117
	39  python3                             0x0000000108b185b1 type_call + 241
	40  python3                             0x0000000108a6adf1 _PyObject_FastCallDict + 177
	41  python3                             0x0000000108bc4348 call_function + 392
	42  python3                             0x0000000108bc1f4c _PyEval_EvalFrameDefault + 47100
	43  python3                             0x0000000108bc45fc fast_function + 188
	44  python3                             0x0000000108bc42ac call_function + 236
	45  python3                             0x0000000108bc1f4c _PyEval_EvalFrameDefault + 47100
	46  python3                             0x0000000108bb5589 _PyEval_EvalCodeWithName + 425
	47  python3                             0x0000000108c0d63c PyRun_FileExFlags + 252
	48  python3                             0x0000000108c0cdee PyRun_SimpleFileExFlags + 366
	49  python3                             0x0000000108c32dd6 Py_Main + 3718
	50  python3                             0x0000000108a62e7d main + 509
	51  libdyld.dylib                       0x00007fff708cf015 start + 1
	52  ???                                 0x0000000000000004 0x0 + 4
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
