### ISSUE TITLE
dataexplore no longer on snap?

### ISSUE THREAD

**Issue by cfskelly** [dmnfarrell/pandastable#85]
Damien, 
Following the Wiki I have tried to download the dataexplore package/application from snap and received the following:
chuck@ThinkCenter:~$ sudo snap install dataexplore
[sudo] password for chuck: 
error: snap "dataexplore" not found
chuck@ThinkCenter:~$ 
I am using WattOS which is UBUNTU 16.04 LTS derivative. I have downloaded all dependencies called for and tested snap by downloading the hello program.
I have pandas also downloaded as well. 

Has this application been removed from snap? 

Chuck

**Comment by dmnfarrell** [comment]
No it's still on snap. You don't need any dependencies installed with a the snap. Do other snaps work on your system? e.g. try one from here: https://snapcraft.io/store

**Comment by cfskelly** [comment]
Damien,
I was able to download and run the Hello world snap. I will try another from the store. Do you have an actual link to where I can find it? I tried a 'find' and it is not showing in the data base.  
Chuck    On Thursday, April 26, 2018, 12:12:35 PM EDT, Damien Farrell <notifications@github.com> wrote:  
 
 
No it's still on snap. You don't need any dependencies installed with a the snap. Do other snaps work on your system? e.g. try one from here: https://snapcraft.io/store

**Comment by dmnfarrell** [comment]
You can install snap files directly but then have to include the --dangerous switch as they are not signed from the store. 
There is a download link here: https://dashboard.snapcraft.io/snaps/dataexplore/revisions/5/download
