### ISSUE TITLE
.deb installer missing

### ISSUE THREAD

**Issue by nitrofurano** [dmnfarrell/pandastable#86]
how can i install from .deb instead of snap?
is there any ppa available?
(snap packages are bloated, takes a huge disk space)

**Comment by dmnfarrell** [comment]
Sorry there's no deb. They are very hard to make and maintain compared to snaps. You can also install with pip, the python package tool: `sudo pip install pandastable` (you can then run the command dataexplore in the terminal). Not sure how much less space this uses exactly. The snap is ~70Mb so is not too bad.
