### ISSUE TITLE
Can't plot dates

### ISSUE THREAD

**Issue by Globoquadrina** [dmnfarrell/pandastable#88]
When I try to plot dates given as YYYY-MM-DD or DD.MM.YYYY against numeric values as a scatter plot, I receive the error **"None Type" object is not iterable**.

**Comment by dmnfarrell** [comment]
I'm not sure a scatter plot is appropriate for time vs number data. Shouldn't you just use a line plot as below. Though the error message should be clearer.

![test](https://user-images.githubusercontent.com/7859189/39517593-289ad0b4-4df8-11e8-85f6-999a235b23ed.png)

**Comment by Globoquadrina** [comment]
My data contains multiple values for a single time, so line plots don't make sense. Is there a way to trick pandastable to plot this?
| Date | Value |
| 01.01.2018 | 12 |
| 01.01.2018 | 26 |
| 01.01.2018 | 34 | 
| 02.01.2018 | 56 |
| 02.01.2018 | 32 |
| 02.01.2018 | 54 |

**Comment by dmnfarrell** [comment]
Even a scatter plot would place all the identical time points in one x coordinate. You want each point separated?

**Comment by Globoquadrina** [comment]
Here is a random example of what I mean:
![example](https://user-images.githubusercontent.com/20252887/39521295-3c2ad442-4e0e-11e8-9032-29e52319a866.PNG)

**Comment by Globoquadrina** [comment]
Any update on this?

**Comment by dmnfarrell** [comment]
Yes sorry I haven't had time to look at this. Will take a look soon and let you know.

**Comment by dmnfarrell** [comment]
I can replicate your plot using a line plot with some minor changes.You set the line width to 0 and tick the errorbar on. It uses the second column selected as the error values. Is that sufficient.

![test](https://user-images.githubusercontent.com/7859189/39949627-e1cd8c16-5573-11e8-872a-5ea1561db09b.png)

**Comment by Globoquadrina** [comment]
Thank you! I will try to reproduce that.

**Comment by dmnfarrell** [comment]
It's a bit tricky. You currently have to also set the date column as the index and make sure you select a marker symbol. Unless you're using the git version though you won't get this update yet. How did you install?
