### ISSUE TITLE
Usability: Base Option/ data/ GroupBy: ungrouping hard to access

### ISSUE THREAD

**Issue by jdittrich** [dmnfarrell/pandastable#90]
**Story:** I use the application for exploratory data analysis. Among other things, I sometimes plot with grouping and then want to ungroup again, since it turned out to be unhelpful. 

**Problem:** One can select a grouping, but one can't select an ungrouping, except by manually deleting the name of the grouped-by column

![image](https://user-images.githubusercontent.com/3416487/41113489-0fdd3296-6a82-11e8-9ca1-2ff195e274c3.png)

**Suggestion:** Have an always included, selected-as-default option called "no grouping"

**Comment by dmnfarrell** [comment]
There is now an empty option you can select to remove grouping.

**Comment by jdittrich** [comment]
Thank you! If you are interested in such usability feedback (which is part of my day job, so it comes pretty natural to me), I'll keep an open eye when I use the tool and let you know.

**Comment by dmnfarrell** [comment]
Sure that would be useful. Thanks.
