### ISSUE TITLE
Column titles in groupBy menu not updated after CSV import

### ISSUE THREAD

**Issue by jdittrich** [dmnfarrell/pandastable#91]
**Version:** 0.9.1
**Steps to reproduce:**  

* Import CSV. It will prompt for the creation of a new sheet. Seemingly it creates a temporary sheet with the columns named a,b,c,d… . Then you finish CSV import by clicking import in the import dialog. 
* Use *group By* controls in the plot frame

**Problem** They still have the names a,b,c… not the current ones created after the CSV import

![image](https://user-images.githubusercontent.com/3416487/41315650-6c101a30-6e90-11e8-8408-aab3c24602de.png)

**Comment by dmnfarrell** [comment]
Yes it may be a bit confusing that it creates the temporary 'empty' sheet. The import steps possibly need to be made a bit simpler. 
This is a bug in not updating the cols in the plot options. I'll take a look.
