### ISSUE TITLE
Callback function not called on redraw() in core.py

### ISSUE THREAD

**Issue by travisjayday** [dmnfarrell/pandastable#92]
Hey there, it seems the callback function is simply not called in redrawVisible() in core.py... The parameter callback is present, it is just never used. Looks like a very easy fix.

**Comment by dmnfarrell** [comment]
Yes sorry this must have been a place holder. However now that I think about it running a callback after redraw might not be very useful since whatever changes you make won't be shown. Maybe the callback should be run at the start of the function?
