### ISSUE TITLE
Pandastable not able to build using cxfreeze

### ISSUE THREAD

**Issue by priyanka22kar** [dmnfarrell/pandastable#94]
import cx_Freeze
import sys
import os

if sys.platform == 'win32':
base = "Win32GUI"

executables = [cx_Freeze.Executable("Cm.py",icon = "48 size.ico", base="Win32GUI")]

PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.file))
os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tcl8.6')
os.environ['TK_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tk8.6')

options = {'build_exe': {"packages": ["os","pandastable"], "includes": ["idna.idnadata"],
'include_files': [os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tk86t.dll'),

                          os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tcl86t.dll'), ], }, }
cx_Freeze.setup(name='MongodbUpdation', version="1.0", description='MongoDB Updation',
options=options, executables=executables)

this is my setup file
I have used pandas table package for my tkinter GUI application
It executes perfectly but when I try to build an application of the same using cxfreeze it gives me an error saying pandastable cannot be imported
what can I do to solve the issue ?
@dmnfarrell please help.
thank you

**Comment by dmnfarrell** [comment]
Did you check my own script to make dataexplore using cxfreeze?
https://github.com/dmnfarrell/pandastable/blob/master/freeze.py

**Comment by priyanka22kar** [comment]
@dmnfarrell 
I saw your freeze.py file
I have my own application where I am downloading and adding the data to mongodb and  using your application to view my mongodb collection
so now here I want to create a build where your pandastable application also has to included but it isnt getting included and that is why i wanted your advice like how I can include it .
Thank you.

**Comment by dmnfarrell** [comment]
It's tricky to tell just by looking. Getting this working is trial and error. You'd just have to see what's missing in yours compared to mine. For example you don't appear to have this part in yours:

`includes = ["pandastable"]`
