### ISSUE TITLE
How to create dropdown menus for my tkinter app

### ISSUE THREAD

**Issue by TarzanWonder** [dmnfarrell/pandastable#96]
Hi,

I am using your library to create one tkinter application which has around 17 headers and unlimited rows. How do i add drop down in few columns in pandastable?

Do i need create tkinter option menu in there 
like below one:
txtname14 = OptionMenu(f1ab, bank, *field)
txtname14.grid(row=1, column=1, sticky=W)

and how do you capture if i edit any cell into database?

**Comment by dmnfarrell** [comment]
I'm not totally clear on what you want to do. You want drop down menus to appear inside the cells? If so you would have to inherit from the table class and override the methods that handle the mouse right click behaviour. I haven't used optionmenus but they seem to be what you need.

**Comment by TarzanWonder** [comment]
I am creating a tkinter application that would your data frame and data from database.This application requires optionmenus for cells. If you can create a function where we can add options menus in required cells would be a great help.

**Comment by dmnfarrell** [comment]
Using the database interface is a different problem but should be easy enough to do. Someone else was asking about that here: https://github.com/dmnfarrell/pandastable/issues/95

For the cell dropdown menus it's possible but would take some time to implement properly. It would require the column type be a categorical one I guess. I am still not sure why you need it. It implies you will need to do a lot of data entry into the table?

**Comment by TarzanWonder** [comment]
So i am creating a distributable application which would be user by 100 of users or even more than that. They have to do lots of data entry on daily basis and looking for some impeccable solution to edit database directly. Drop down menus is indeed a life savior as it will save lots of time.

For editing cell and change the entries and updating the database, can you please provide a small code example to me and to as well as to other user. I guess pandas has no option to use get method or StringVar() method to update database. 


One more option thing ,how do you freeze columns if you don't want them to be editable? Like freezing them so that user cannot edit it?

These above queries would be a helping hand if we get these into creating application where we have to use table in tkinter

**Comment by dmnfarrell** [comment]
The widget doesn't handle database sources directly but pandas has methods to do this. As long as you can update the underlying dataframe all you need do is refresh the table. For data entry you would write back out to sql. I am not sure how efficient this is in terms of updating tables in an existing database. I could write a simple example script to check.

However handling many users at once I am not sure if this is the solution you need. You should test it on simple examples I guess.
Remember the widget is mostly for table analysis even though you can do data entry. If you know Python I would recommend you sub-class the widget and implement your own data entry methods. I can point to the methods you would need to override. 

You can't currently freeze columns but you could also implement that in your sub-class. It wouldn't be too hard.

**Comment by TarzanWonder** [comment]
Please write a sample script to check on how to update the database after editing cells directly. Please do share it publicy or update the docs as they would be very helpful.

I can write down a subclass for an optionmenu widget that would take my given options. Please do guide me

For freezing the cells i can write down the query that would not update the database of the non empty cells.

I'll update you once I write the drop down class. Please update once you get to know about updating the database after editing cell

**Comment by dmnfarrell** [comment]
Did you fix this issue? Sorry I didn't have time to look into this.

**Comment by TarzanWonder** [comment]
Yes i fixed that database thing. But looking for the drop down menu option. Which is not fixed by me yet

**Comment by dmnfarrell** [comment]
Is this resolved now.

**Comment by TarzanWonder** [comment]
Nope, not yet... Are you doing it

**Comment by TarzanWonder** [comment]
Please incorporate it. I will use this example into my application

**Comment by dmnfarrell** [comment]
Ok this is functionality is now added to the Table class so you may not need to sub-class. To add values outside the original categories you need to convert back to object type.
