### ISSUE TITLE
Reference to non-existent method in class

### ISSUE THREAD

**Issue by DerFrischmaker** [dmnfarrell/pandastable#98]
https://github.com/dmnfarrell/pandastable/blob/ea3d6bde2bc989070603ed91d4280c122b4fc80b/pandastable/data.py#L171

The method 'getRecName' referenced at Line 171 in module data.py does not exist and causes an error when 'getRecordAtRow' is called.

**Comment by dmnfarrell** [comment]
Thanks that's fixed though getRecordAtRow is somewhat redundant in that you can just call df.iloc[row] on the underlying dataframe to get the row data. But I will leave this method in data.py.

**Comment by DerFrischmaker** [comment]
Agreed that it's redundant and I do the same to access the row instead of using this method, though I found the bug at first because I was trying to stick to the higher level API calls. (BTW, very nice interface!)

**Comment by dmnfarrell** [comment]
The original table used a dictionary for the backend so some of the methods in data.py are a legacy from that. Cheers.
