### ISSUE TITLE
FindReplaceDialog is not working

### ISSUE THREAD

**Issue by TarzanWonder** [dmnfarrell/pandastable#99]
Hi,
can you please resolve this issue as FindReplaceDialog is not activated yet?

**Comment by dmnfarrell** [comment]
Yes it's not implemented yet. I'll take a look at it.

**Comment by TarzanWonder** [comment]
Please do take a look. Rest i have managed all. Implemented it with database, just find and replace pending

**Comment by dmnfarrell** [comment]
@TarzanWonder how does this relate to the pull request?

**Comment by dmnfarrell** [comment]
This basically works now but needs some tweaks. You have to be using the git version to see the changes.

**Comment by TarzanWonder** [comment]
I will uninstall and re-install it. Does it provide bind of control-c?

**Comment by dmnfarrell** [comment]
Yes. BTW this won't work well for large tables. I need to optimise it by updating the redraw method.

**Comment by TarzanWonder** [comment]
Please do it

**Comment by dmnfarrell** [comment]
This should now work pretty well for most tables.
